// Code generated by fullend gen — do not edit.
package gigstate

import (
	"fmt"
	"os"
)

// State constants.
const (
	StateCompleted = "completed"
	StateDisputed = "disputed"
	StateDraft = "draft"
	StateInProgress = "in_progress"
	StateOpen = "open"
	StateUnderReview = "under_review"
)

// Input holds the state field value for transition checks.
type Input struct {
	Status interface{}
}

type transitionKey struct {
	from  string
	event string
}

var transitions = map[transitionKey]string{
	{"draft", "PublishGig"}: "open",
	{"open", "AcceptProposal"}: "in_progress",
	{"in_progress", "SubmitWork"}: "under_review",
	{"under_review", "ApproveWork"}: "completed",
	{"under_review", "RaiseDispute"}: "disputed",
}

// CanTransition checks if the given event is valid from the current state.
// Set DISABLE_STATE_CHECK=1 to bypass state transition checks.
func CanTransition(input Input, event string) error {
	if os.Getenv("DISABLE_STATE_CHECK") == "1" {
		return nil
	}
	status, _ := input.Status.(string)
	_, ok := transitions[transitionKey{from: status, event: event}]
	if !ok {
		return fmt.Errorf("cannot transition from %q via %q", status, event)
	}
	return nil
}
