// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Action defines model for Action.
type Action struct {
	ActionType      *string `json:"action_type,omitempty"`
	Id              *int64  `json:"id,omitempty"`
	PayloadTemplate *string `json:"payload_template,omitempty"`
	SequenceOrder   *int64  `json:"sequence_order,omitempty"`
	WorkflowId      *int64  `json:"workflow_id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// ExecutionLog defines model for ExecutionLog.
type ExecutionLog struct {
	CreditsSpent *int64     `json:"credits_spent,omitempty"`
	ExecutedAt   *time.Time `json:"executed_at,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	OrgId        *int64     `json:"org_id,omitempty"`
	ReportKey    *string    `json:"report_key,omitempty"`
	Status       *string    `json:"status,omitempty"`
	WorkflowId   *int64     `json:"workflow_id,omitempty"`
}

// Organization defines model for Organization.
type Organization struct {
	CreditsBalance *int64  `json:"credits_balance,omitempty"`
	Id             *int64  `json:"id,omitempty"`
	Name           *string `json:"name,omitempty"`
	PlanType       *string `json:"plan_type,omitempty"`
}

// Template defines model for Template.
type Template struct {
	Category         *string    `json:"category,omitempty"`
	CloneCount       *int64     `json:"clone_count,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Id               *int64     `json:"id,omitempty"`
	OrgId            *int64     `json:"org_id,omitempty"`
	SourceWorkflowId *int64     `json:"source_workflow_id,omitempty"`
	Title            *string    `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Id    *int64  `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	OrgId *int64  `json:"org_id,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// Webhook defines model for Webhook.
type Webhook struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	EventType *string    `json:"event_type,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	OrgId     *int64     `json:"org_id,omitempty"`
	Url       *string    `json:"url,omitempty"`
}

// Workflow defines model for Workflow.
type Workflow struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	OrgId          *int64     `json:"org_id,omitempty"`
	RootWorkflowId *int64     `json:"root_workflow_id,omitempty"`
	Status         *string    `json:"status,omitempty"`
	Title          *string    `json:"title,omitempty"`
	TriggerEvent   *string    `json:"trigger_event,omitempty"`
	Version        *int64     `json:"version,omitempty"`
}

// CreateOrganizationJSONBody defines parameters for CreateOrganization.
type CreateOrganizationJSONBody struct {
	CreditsBalance int64  `json:"credits_balance"`
	Name           string `json:"name"`
	PlanType       string `json:"plan_type"`
}

// PublishTemplateJSONBody defines parameters for PublishTemplate.
type PublishTemplateJSONBody struct {
	Category         string `json:"category"`
	Description      string `json:"description"`
	SourceWorkflowId int64  `json:"source_workflow_id"`
	Title            string `json:"title"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	OrgId    int64               `json:"org_id"`
	Password string              `json:"password"`
	Role     string              `json:"role"`
}

// CreateWebhookJSONBody defines parameters for CreateWebhook.
type CreateWebhookJSONBody struct {
	EventType string `json:"event_type"`
	Url       string `json:"url"`
}

// CreateWorkflowJSONBody defines parameters for CreateWorkflow.
type CreateWorkflowJSONBody struct {
	Title        string `json:"title"`
	TriggerEvent string `json:"trigger_event"`
}

// AddActionJSONBody defines parameters for AddAction.
type AddActionJSONBody struct {
	ActionType      string `json:"action_type"`
	PayloadTemplate string `json:"payload_template"`
	SequenceOrder   int64  `json:"sequence_order"`
}

// SetScheduleJSONBody defines parameters for SetSchedule.
type SetScheduleJSONBody struct {
	Cron string `json:"cron"`
}

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody CreateOrganizationJSONBody

// PublishTemplateJSONRequestBody defines body for PublishTemplate for application/json ContentType.
type PublishTemplateJSONRequestBody PublishTemplateJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// CreateWebhookJSONRequestBody defines body for CreateWebhook for application/json ContentType.
type CreateWebhookJSONRequestBody CreateWebhookJSONBody

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody CreateWorkflowJSONBody

// AddActionJSONRequestBody defines body for AddAction for application/json ContentType.
type AddActionJSONRequestBody AddActionJSONBody

// SetScheduleJSONRequestBody defines body for SetSchedule for application/json ContentType.
type SetScheduleJSONRequestBody SetScheduleJSONBody
