// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

package db

import (
	"context"
)

const executionLogCreate = `-- name: ExecutionLogCreate :one
INSERT INTO execution_logs (workflow_id, org_id, status, credits_spent)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, org_id, status, credits_spent, report_key, executed_at
`

type ExecutionLogCreateParams struct {
	WorkflowID   int64  `json:"workflow_id"`
	OrgID        int64  `json:"org_id"`
	Status       string `json:"status"`
	CreditsSpent int64  `json:"credits_spent"`
}

func (q *Queries) ExecutionLogCreate(ctx context.Context, arg ExecutionLogCreateParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, executionLogCreate,
		arg.WorkflowID,
		arg.OrgID,
		arg.Status,
		arg.CreditsSpent,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ReportKey,
		&i.ExecutedAt,
	)
	return i, err
}

const executionLogCreateWithReport = `-- name: ExecutionLogCreateWithReport :one
INSERT INTO execution_logs (workflow_id, org_id, status, credits_spent, report_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, org_id, status, credits_spent, report_key, executed_at
`

type ExecutionLogCreateWithReportParams struct {
	WorkflowID   int64  `json:"workflow_id"`
	OrgID        int64  `json:"org_id"`
	Status       string `json:"status"`
	CreditsSpent int64  `json:"credits_spent"`
	ReportKey    string `json:"report_key"`
}

func (q *Queries) ExecutionLogCreateWithReport(ctx context.Context, arg ExecutionLogCreateWithReportParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, executionLogCreateWithReport,
		arg.WorkflowID,
		arg.OrgID,
		arg.Status,
		arg.CreditsSpent,
		arg.ReportKey,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ReportKey,
		&i.ExecutedAt,
	)
	return i, err
}

const executionLogFindByIDAndOrgID = `-- name: ExecutionLogFindByIDAndOrgID :one
SELECT id, workflow_id, org_id, status, credits_spent, report_key, executed_at FROM execution_logs WHERE id = $1 AND org_id = $2
`

type ExecutionLogFindByIDAndOrgIDParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) ExecutionLogFindByIDAndOrgID(ctx context.Context, arg ExecutionLogFindByIDAndOrgIDParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, executionLogFindByIDAndOrgID, arg.ID, arg.OrgID)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ReportKey,
		&i.ExecutedAt,
	)
	return i, err
}

const executionLogListByWorkflowID = `-- name: ExecutionLogListByWorkflowID :many
SELECT id, workflow_id, org_id, status, credits_spent, report_key, executed_at FROM execution_logs WHERE workflow_id = $1 ORDER BY executed_at DESC
`

func (q *Queries) ExecutionLogListByWorkflowID(ctx context.Context, workflowID int64) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, executionLogListByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.OrgID,
			&i.Status,
			&i.CreditsSpent,
			&i.ReportKey,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
