// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"
)

const templateCreate = `-- name: TemplateCreate :one
INSERT INTO templates (source_workflow_id, org_id, title, description, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source_workflow_id, org_id, title, description, category, clone_count, created_at
`

type TemplateCreateParams struct {
	SourceWorkflowID int64  `json:"source_workflow_id"`
	OrgID            int64  `json:"org_id"`
	Title            string `json:"title"`
	Description      string `json:"description"`
	Category         string `json:"category"`
}

func (q *Queries) TemplateCreate(ctx context.Context, arg TemplateCreateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, templateCreate,
		arg.SourceWorkflowID,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CloneCount,
		&i.CreatedAt,
	)
	return i, err
}

const templateFindByID = `-- name: TemplateFindByID :one
SELECT id, source_workflow_id, org_id, title, description, category, clone_count, created_at FROM templates WHERE id = $1
`

func (q *Queries) TemplateFindByID(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, templateFindByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CloneCount,
		&i.CreatedAt,
	)
	return i, err
}

const templateFindBySourceWorkflowID = `-- name: TemplateFindBySourceWorkflowID :one
SELECT id, source_workflow_id, org_id, title, description, category, clone_count, created_at FROM templates WHERE source_workflow_id = $1
`

func (q *Queries) TemplateFindBySourceWorkflowID(ctx context.Context, sourceWorkflowID int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, templateFindBySourceWorkflowID, sourceWorkflowID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CloneCount,
		&i.CreatedAt,
	)
	return i, err
}

const templateIncrementCloneCount = `-- name: TemplateIncrementCloneCount :exec
UPDATE templates SET clone_count = clone_count + 1 WHERE id = $1
`

func (q *Queries) TemplateIncrementCloneCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, templateIncrementCloneCount, id)
	return err
}

const templateList = `-- name: TemplateList :many
SELECT id, source_workflow_id, org_id, title, description, category, clone_count, created_at FROM templates
`

func (q *Queries) TemplateList(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, templateList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CloneCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
