// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
)

const webhookCreate = `-- name: WebhookCreate :one
INSERT INTO webhooks (org_id, url, event_type)
VALUES ($1, $2, $3)
RETURNING id, org_id, url, event_type, created_at
`

type WebhookCreateParams struct {
	OrgID     int64  `json:"org_id"`
	Url       string `json:"url"`
	EventType string `json:"event_type"`
}

func (q *Queries) WebhookCreate(ctx context.Context, arg WebhookCreateParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, webhookCreate, arg.OrgID, arg.Url, arg.EventType)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}

const webhookDelete = `-- name: WebhookDelete :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) WebhookDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, webhookDelete, id)
	return err
}

const webhookFindByID = `-- name: WebhookFindByID :one
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) WebhookFindByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, webhookFindByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}

const webhookFindByIDAndOrgID = `-- name: WebhookFindByIDAndOrgID :one
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE id = $1 AND org_id = $2
`

type WebhookFindByIDAndOrgIDParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) WebhookFindByIDAndOrgID(ctx context.Context, arg WebhookFindByIDAndOrgIDParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, webhookFindByIDAndOrgID, arg.ID, arg.OrgID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}

const webhookListByOrgID = `-- name: WebhookListByOrgID :many
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE org_id = $1
`

func (q *Queries) WebhookListByOrgID(ctx context.Context, orgID int64) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, webhookListByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webhookListByOrgIDAndEventType = `-- name: WebhookListByOrgIDAndEventType :many
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE org_id = $1 AND event_type = $2
`

type WebhookListByOrgIDAndEventTypeParams struct {
	OrgID     int64  `json:"org_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) WebhookListByOrgIDAndEventType(ctx context.Context, arg WebhookListByOrgIDAndEventTypeParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, webhookListByOrgIDAndEventType, arg.OrgID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
