// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposals.sql

package db

import (
	"context"
)

const proposalCreate = `-- name: ProposalCreate :one
INSERT INTO proposals (gig_id, freelancer_id, bid_amount)
VALUES ($1, $2, $3)
RETURNING id, gig_id, freelancer_id, bid_amount, status
`

type ProposalCreateParams struct {
	GigID        int64 `json:"gig_id"`
	FreelancerID int64 `json:"freelancer_id"`
	BidAmount    int64 `json:"bid_amount"`
}

func (q *Queries) ProposalCreate(ctx context.Context, arg ProposalCreateParams) (Proposal, error) {
	row := q.db.QueryRowContext(ctx, proposalCreate, arg.GigID, arg.FreelancerID, arg.BidAmount)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.GigID,
		&i.FreelancerID,
		&i.BidAmount,
		&i.Status,
	)
	return i, err
}

const proposalFindByID = `-- name: ProposalFindByID :one
SELECT id, gig_id, freelancer_id, bid_amount, status FROM proposals WHERE id = $1
`

func (q *Queries) ProposalFindByID(ctx context.Context, id int64) (Proposal, error) {
	row := q.db.QueryRowContext(ctx, proposalFindByID, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.GigID,
		&i.FreelancerID,
		&i.BidAmount,
		&i.Status,
	)
	return i, err
}

const proposalUpdateStatus = `-- name: ProposalUpdateStatus :exec
UPDATE proposals SET status = $1 WHERE id = $2
`

type ProposalUpdateStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) ProposalUpdateStatus(ctx context.Context, arg ProposalUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, proposalUpdateStatus, arg.Status, arg.ID)
	return err
}
