// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

package db

import (
	"context"
)

const executionLogCreate = `-- name: ExecutionLogCreate :one
INSERT INTO execution_logs (workflow_id, org_id)
VALUES ($1, $2)
RETURNING id, workflow_id, org_id, status, credits_spent, executed_at
`

type ExecutionLogCreateParams struct {
	WorkflowID int64 `json:"workflow_id"`
	OrgID      int64 `json:"org_id"`
}

func (q *Queries) ExecutionLogCreate(ctx context.Context, arg ExecutionLogCreateParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, executionLogCreate, arg.WorkflowID, arg.OrgID)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}

const executionLogListByOrg = `-- name: ExecutionLogListByOrg :many
SELECT id, workflow_id, org_id, status, credits_spent, executed_at FROM execution_logs WHERE org_id = $1 ORDER BY executed_at DESC
`

func (q *Queries) ExecutionLogListByOrg(ctx context.Context, orgID int64) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, executionLogListByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.OrgID,
			&i.Status,
			&i.CreditsSpent,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
