apiVersion: fullend/v1
kind: Project

metadata:
  name: dummy-study

backend:
  lang: go
  framework: gin
  module: github.com/geul-org/dummy-study
  middleware:
    - bearerAuth

frontend:
  lang: typescript
  framework: react
  bundler: vite
  name: dummy-study-web
