// Code generated by fullend gen — do not edit.
//fullend:gen ssot=states/workflow.md contract=72e53b8
package workflowstate

import (
	"fmt"
	"os"
)

// State constants.
const (
	StateActive = "active"
	StateArchived = "archived"
	StateDraft = "draft"
	StatePaused = "paused"
)

// Input holds the state field value for transition checks.
type Input struct {
	Status interface{}
}

type transitionKey struct {
	from  string
	event string
}

var transitions = map[transitionKey]string{
	{"draft", "ActivateWorkflow"}: "active",
	{"active", "PauseWorkflow"}: "paused",
	{"paused", "ActivateWorkflow"}: "active",
	{"active", "ArchiveWorkflow"}: "archived",
	{"active", "ExecuteWorkflow"}: "active",
	{"active", "ExecuteWithReport"}: "active",
}

// CanTransition checks if the given event is valid from the current state.
// Set DISABLE_STATE_CHECK=1 to bypass state transition checks.
func CanTransition(input Input, event string) error {
	if os.Getenv("DISABLE_STATE_CHECK") == "1" {
		return nil
	}
	status, _ := input.Status.(string)
	_, ok := transitions[transitionKey{from: status, event: event}]
	if !ok {
		return fmt.Errorf("cannot transition from %q via %q", status, event)
	}
	return nil
}
