package genmodel

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ettle/strcase"
	"github.com/getkin/kin-openapi/openapi3"
)

// Generate reads an OpenAPI source (file path or URL), generates a Go model file,
// and writes it to outputDir.
func Generate(source, outputDir string) error {
	data, err := readSource(source)
	if err != nil {
		return fmt.Errorf("read source: %w", err)
	}

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromData(data)
	if err != nil {
		return fmt.Errorf("parse OpenAPI: %w", err)
	}
	if err := doc.Validate(loader.Context); err != nil {
		return fmt.Errorf("validate OpenAPI: %w", err)
	}

	serviceName := inferServiceName(source, doc)
	code, err := generateCode(serviceName, doc)
	if err != nil {
		return fmt.Errorf("generate code: %w", err)
	}

	outFile := filepath.Join(outputDir, strings.ToLower(serviceName)+".go")
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(outFile, code, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	fmt.Printf("✓ gen-model   %s → %s\n", serviceName, outFile)
	return nil
}

// GenerateBytes generates code and returns it as bytes (for testing).
func GenerateBytes(source string, data []byte) ([]byte, error) {
	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromData(data)
	if err != nil {
		return nil, fmt.Errorf("parse OpenAPI: %w", err)
	}
	if err := doc.Validate(loader.Context); err != nil {
		return nil, fmt.Errorf("validate OpenAPI: %w", err)
	}
	serviceName := inferServiceName(source, doc)
	return generateCode(serviceName, doc)
}

func readSource(source string) ([]byte, error) {
	if strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://") {
		resp, err := http.Get(source)
		if err != nil {
			return nil, fmt.Errorf("fetch URL: %w", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("fetch URL: status %d", resp.StatusCode)
		}
		return io.ReadAll(resp.Body)
	}
	return os.ReadFile(source)
}

func inferServiceName(source string, doc *openapi3.T) string {
	if doc.Info != nil && doc.Info.Title != "" {
		return toPascalCase(doc.Info.Title)
	}
	base := filepath.Base(source)
	// Strip known suffixes: .openapi.yaml, .openapi.json, .yaml, .json
	for _, suffix := range []string{".openapi.yaml", ".openapi.json", ".openapi.yml", ".yaml", ".yml", ".json"} {
		if strings.HasSuffix(base, suffix) {
			base = base[:len(base)-len(suffix)]
			break
		}
	}
	return toPascalCase(base)
}

func generateCode(serviceName string, doc *openapi3.T) ([]byte, error) {
	var buf bytes.Buffer

	methods := extractMethods(doc)
	types := extractResponseTypes(serviceName, methods, doc)
	needsTime := typesNeedTime(types)

	// Header
	buf.WriteString("// Code generated by fullend gen-model. DO NOT EDIT.\n")
	buf.WriteString("package external\n\n")

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/http\"\n")
	if needsTime {
		buf.WriteString("\t\"time\"\n")
	}
	buf.WriteString(")\n\n")

	// Interface
	fmt.Fprintf(&buf, "type %sModel interface {\n", serviceName)
	for _, m := range methods {
		fmt.Fprintf(&buf, "\t%s\n", m.signature())
	}
	buf.WriteString("}\n\n")

	// Response types
	for _, t := range types {
		fmt.Fprintf(&buf, "type %s struct {\n", t.Name)
		for _, f := range t.Fields {
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", f.Name, f.GoType, f.JSONName)
		}
		buf.WriteString("}\n\n")
	}

	// Client struct
	lowerName := lcFirst(serviceName)
	fmt.Fprintf(&buf, "type %sClient struct {\n", lowerName)
	buf.WriteString("\tbaseURL string\n")
	buf.WriteString("\tclient  *http.Client\n")
	buf.WriteString("}\n\n")

	// Constructor
	fmt.Fprintf(&buf, "func New%sModel(baseURL string) %sModel {\n", serviceName, serviceName)
	fmt.Fprintf(&buf, "\treturn &%sClient{baseURL: baseURL, client: &http.Client{}}\n", lowerName)
	buf.WriteString("}\n\n")

	// Method implementations
	for _, m := range methods {
		buf.WriteString(m.implementation(lowerName + "Client"))
		buf.WriteString("\n")
	}

	// do() helper
	buf.WriteString(doHelper(lowerName + "Client"))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n--- raw ---\n%s", err, buf.String())
	}
	return formatted, nil
}

type methodInfo struct {
	Name       string
	HTTPMethod string
	Path       string
	Params     []paramInfo
	ReturnType string // empty = error only
}

type paramInfo struct {
	Name   string
	GoType string
	In     string // "body", "path"
}

func (m methodInfo) signature() string {
	var params []string
	params = append(params, "ctx context.Context")
	for _, p := range m.Params {
		params = append(params, fmt.Sprintf("%s %s", p.Name, p.GoType))
	}
	if m.ReturnType != "" {
		return fmt.Sprintf("%s(%s) (*%s, error)", m.Name, strings.Join(params, ", "), m.ReturnType)
	}
	return fmt.Sprintf("%s(%s) error", m.Name, strings.Join(params, ", "))
}

func (m methodInfo) implementation(receiverType string) string {
	var buf bytes.Buffer

	var params []string
	params = append(params, "ctx context.Context")
	for _, p := range m.Params {
		params = append(params, fmt.Sprintf("%s %s", p.Name, p.GoType))
	}

	if m.ReturnType != "" {
		fmt.Fprintf(&buf, "func (c *%s) %s(%s) (*%s, error) {\n", receiverType, m.Name, strings.Join(params, ", "), m.ReturnType)
	} else {
		fmt.Fprintf(&buf, "func (c *%s) %s(%s) error {\n", receiverType, m.Name, strings.Join(params, ", "))
	}

	// Build path with path params
	pathExpr := m.buildPathExpr()

	// Build body for POST/PUT/PATCH
	hasBody := m.HTTPMethod == "POST" || m.HTTPMethod == "PUT" || m.HTTPMethod == "PATCH"
	bodyParams := m.bodyParams()

	if hasBody && len(bodyParams) > 0 {
		buf.WriteString("\tbody := map[string]any{")
		for i, p := range bodyParams {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%q: %s", p.Name, p.Name)
		}
		buf.WriteString("}\n")
	}

	if m.ReturnType != "" {
		fmt.Fprintf(&buf, "\tvar resp %s\n", m.ReturnType)
		if hasBody && len(bodyParams) > 0 {
			fmt.Fprintf(&buf, "\tif err := c.do(ctx, %q, %s, body, &resp); err != nil {\n", m.HTTPMethod, pathExpr)
		} else {
			fmt.Fprintf(&buf, "\tif err := c.do(ctx, %q, %s, nil, &resp); err != nil {\n", m.HTTPMethod, pathExpr)
		}
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &resp, nil\n")
	} else {
		if hasBody && len(bodyParams) > 0 {
			fmt.Fprintf(&buf, "\treturn c.do(ctx, %q, %s, body, nil)\n", m.HTTPMethod, pathExpr)
		} else {
			fmt.Fprintf(&buf, "\treturn c.do(ctx, %q, %s, nil, nil)\n", m.HTTPMethod, pathExpr)
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

func (m methodInfo) buildPathExpr() string {
	pathParams := m.pathParams()
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", m.Path)
	}
	// Replace {param} with %v and build fmt.Sprintf
	path := m.Path
	var args []string
	for _, p := range pathParams {
		placeholder := "{" + p.Name + "}"
		if strings.Contains(path, placeholder) {
			path = strings.Replace(path, placeholder, "%v", 1)
			args = append(args, p.Name)
		}
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", path, strings.Join(args, ", "))
}

func (m methodInfo) bodyParams() []paramInfo {
	var result []paramInfo
	for _, p := range m.Params {
		if p.In == "body" {
			result = append(result, p)
		}
	}
	return result
}

func (m methodInfo) pathParams() []paramInfo {
	var result []paramInfo
	for _, p := range m.Params {
		if p.In == "path" {
			result = append(result, p)
		}
	}
	return result
}

func extractMethods(doc *openapi3.T) []methodInfo {
	var methods []methodInfo
	if doc.Paths == nil {
		return methods
	}

	// Sort paths for deterministic output
	paths := make([]string, 0, len(doc.Paths.Map()))
	for p := range doc.Paths.Map() {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, path := range paths {
		pi := doc.Paths.Map()[path]
		for _, httpMethod := range []string{"GET", "POST", "PUT", "PATCH", "DELETE"} {
			op := pi.GetOperation(httpMethod)
			if op == nil || op.OperationID == "" {
				continue
			}

			m := methodInfo{
				Name:       toPascalCase(op.OperationID),
				HTTPMethod: httpMethod,
				Path:       path,
			}

			// Path parameters
			for _, p := range op.Parameters {
				if p.Value != nil && p.Value.In == "path" {
					m.Params = append(m.Params, paramInfo{
						Name:   toCamelCase(p.Value.Name),
						GoType: schemaToGoType(p.Value.Schema),
						In:     "path",
					})
				}
			}

			// Request body parameters
			if op.RequestBody != nil && op.RequestBody.Value != nil {
				ct := op.RequestBody.Value.Content.Get("application/json")
				if ct != nil && ct.Schema != nil && ct.Schema.Value != nil {
					propNames := sortedKeys(ct.Schema.Value.Properties)
					for _, name := range propNames {
						ref := ct.Schema.Value.Properties[name]
						m.Params = append(m.Params, paramInfo{
							Name:   toCamelCase(name),
							GoType: schemaToGoType(ref),
							In:     "body",
						})
					}
				}
			}

			// Response type
			if resp, ok := op.Responses.Map()["200"]; ok && resp.Value != nil {
				ct := resp.Value.Content.Get("application/json")
				if ct != nil && ct.Schema != nil && ct.Schema.Value != nil {
					m.ReturnType = toPascalCase(op.OperationID) + "Response"
				}
			}

			methods = append(methods, m)
		}
	}

	return methods
}

type structType struct {
	Name   string
	Fields []structField
}

type structField struct {
	Name     string
	GoType   string
	JSONName string
}

func extractResponseTypes(serviceName string, methods []methodInfo, doc *openapi3.T) []structType {
	var types []structType

	for _, m := range methods {
		if m.ReturnType == "" {
			continue
		}

		op := findOperation(doc, m.HTTPMethod, m.Path)
		if op == nil {
			continue
		}

		resp, ok := op.Responses.Map()["200"]
		if !ok || resp.Value == nil {
			continue
		}
		ct := resp.Value.Content.Get("application/json")
		if ct == nil || ct.Schema == nil || ct.Schema.Value == nil {
			continue
		}

		st := structType{Name: m.ReturnType}
		propNames := sortedKeys(ct.Schema.Value.Properties)
		for _, name := range propNames {
			ref := ct.Schema.Value.Properties[name]
			st.Fields = append(st.Fields, structField{
				Name:     toPascalCase(name),
				GoType:   schemaToGoType(ref),
				JSONName: name,
			})
		}
		if len(st.Fields) > 0 {
			types = append(types, st)
		}
	}

	return types
}

func findOperation(doc *openapi3.T, method, path string) *openapi3.Operation {
	if doc.Paths == nil {
		return nil
	}
	pi := doc.Paths.Find(path)
	if pi == nil {
		return nil
	}
	return pi.GetOperation(method)
}

func schemaToGoType(ref *openapi3.SchemaRef) string {
	if ref == nil || ref.Value == nil {
		return "any"
	}
	s := ref.Value
	types := s.Type.Slice()
	if len(types) == 0 {
		// No type specified (e.g. anyOf, oneOf, allOf, or untyped)
		return "any"
	}
	switch types[0] {
	case "integer":
		switch s.Format {
		case "int32":
			return "int32"
		case "int64":
			return "int64"
		default:
			return "int"
		}
	case "number":
		switch s.Format {
		case "float":
			return "float32"
		default:
			return "float64"
		}
	case "string":
		if s.Format == "date-time" {
			return "time.Time"
		}
		return "string"
	case "boolean":
		return "bool"
	case "array":
		if s.Items != nil {
			return "[]" + schemaToGoType(s.Items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func typesNeedTime(types []structType) bool {
	for _, t := range types {
		for _, f := range t.Fields {
			if f.GoType == "time.Time" {
				return true
			}
		}
	}
	return false
}

func doHelper(receiverType string) string {
	return fmt.Sprintf(`func (c *%s) do(ctx context.Context, method, path string, body any, result any) error {
	var buf bytes.Buffer
	if body != nil {
		if err := json.NewEncoder(&buf).Encode(body); err != nil {
			return fmt.Errorf("encode request: %%w", err)
		}
	}
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, &buf)
	if err != nil {
		return fmt.Errorf("create request: %%w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("http %%s %%s: %%w", method, path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("http %%s %%s: status %%d", method, path, resp.StatusCode)
	}
	if result != nil {
		if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
			return fmt.Errorf("decode response: %%w", err)
		}
	}
	return nil
}
`, receiverType)
}

// --- String helpers ---

func toPascalCase(s string) string {
	return strcase.ToGoPascal(s)
}

func toCamelCase(s string) string {
	return strcase.ToGoCamel(s)
}

func lcFirst(s string) string {
	return strcase.ToGoCamel(s)
}

func sortedKeys(m openapi3.Schemas) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
