package genmodel

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
)

func TestGenerateEscrow(t *testing.T) {
	data, err := os.ReadFile("testdata/escrow.openapi.yaml")
	if err != nil {
		t.Fatal(err)
	}

	code, err := GenerateBytes("escrow.openapi.yaml", data)
	if err != nil {
		t.Fatal(err)
	}
	src := string(code)

	// Interface
	if !strings.Contains(src, "type EscrowModel interface {") {
		t.Error("missing EscrowModel interface")
	}

	// Methods
	for _, method := range []string{"Hold(", "Release(", "GetStatus(", "Cancel("} {
		if !strings.Contains(src, method) {
			t.Errorf("missing method %s", method)
		}
	}

	// Response types
	for _, typ := range []string{"HoldResponse", "ReleaseResponse", "GetStatusResponse"} {
		if !strings.Contains(src, "type "+typ+" struct {") {
			t.Errorf("missing response type %s", typ)
		}
	}

	// Cancel has no 200 response, should return error only
	if strings.Contains(src, "CancelResponse") {
		t.Error("Cancel should not have a response type (204 only)")
	}

	// Constructor
	if !strings.Contains(src, "func NewEscrowModel(baseURL string) EscrowModel {") {
		t.Error("missing constructor")
	}

	// Client struct
	if !strings.Contains(src, "escrowClient struct {") {
		t.Error("missing client struct")
	}

	// do() helper
	if !strings.Contains(src, "func (c *escrowClient) do(") {
		t.Error("missing do() helper")
	}

	// Path parameter in GetStatus
	if !strings.Contains(src, "fmt.Sprintf(\"/escrow/%v\"") {
		t.Error("missing path parameter formatting in GetStatus")
	}

	// Generated header
	if !strings.Contains(src, "Code generated by fullend gen-model. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	// context.Context parameter
	if !strings.Contains(src, "ctx context.Context") {
		t.Error("missing context.Context parameter")
	}
}

func TestGenerateWriteFile(t *testing.T) {
	tmpDir := t.TempDir()
	err := Generate("testdata/escrow.openapi.yaml", tmpDir)
	if err != nil {
		t.Fatal(err)
	}

	outFile := filepath.Join(tmpDir, "escrow.go")
	if _, err := os.Stat(outFile); os.IsNotExist(err) {
		t.Error("output file not created")
	}
}

func TestInferServiceName(t *testing.T) {
	tests := []struct {
		source string
		title  string
		want   string
	}{
		{"escrow.openapi.yaml", "", "Escrow"},
		{"my-service.openapi.yaml", "", "MyService"},
		{"stripe.yaml", "", "Stripe"},
		{"anything.yaml", "Payment Gateway", "PaymentGateway"},
		{"https://api.example.com/openapi.yaml", "", "Openapi"}, // fallback to filename
	}

	for _, tt := range tests {
		doc := &openapi3.T{}
		if tt.title != "" {
			doc.Info = &openapi3.Info{Title: tt.title}
		}
		got := inferServiceName(tt.source, doc)
		if got != tt.want {
			t.Errorf("inferServiceName(%q, title=%q) = %q, want %q", tt.source, tt.title, got, tt.want)
		}
	}
}

func TestSchemaToGoType(t *testing.T) {
	tests := []struct {
		typ    string
		format string
		want   string
	}{
		{"integer", "int64", "int64"},
		{"integer", "int32", "int32"},
		{"integer", "", "int"},
		{"number", "float", "float32"},
		{"number", "double", "float64"},
		{"number", "", "float64"},
		{"string", "", "string"},
		{"string", "date-time", "time.Time"},
		{"boolean", "", "bool"},
	}

	for _, tt := range tests {
		s := &openapi3.SchemaRef{
			Value: &openapi3.Schema{
				Type:   &openapi3.Types{tt.typ},
				Format: tt.format,
			},
		}
		got := schemaToGoType(s)
		if got != tt.want {
			t.Errorf("schemaToGoType(%s/%s) = %q, want %q", tt.typ, tt.format, got, tt.want)
		}
	}
}
