package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	ssacparser "github.com/geul-org/ssac/parser"
	ssacvalidator "github.com/geul-org/ssac/validator"
)

// GlueInput holds everything needed to generate glue code.
type GlueInput struct {
	ArtifactsDir string
	SpecsDir     string
	ModulePath   string
	OpenAPIDoc   *openapi3.T
	SymbolTable  *ssacvalidator.SymbolTable
	ServiceFuncs []ssacparser.ServiceFunc
	STMLDeps     map[string]string // dependencies from stml generator
	STMLPages    []string          // page names generated by stml
	STMLPageOps  map[string]string // page file name → primary operationID
}

// internalDir returns the backend/internal/ base path.
func internalDir(artifactsDir string) string {
	return filepath.Join(artifactsDir, "backend", "internal")
}

// Generate creates all glue code files.
func Generate(input *GlueInput) error {
	intDir := internalDir(input.ArtifactsDir)
	if err := os.MkdirAll(intDir, 0755); err != nil {
		return fmt.Errorf("create internal dir: %w", err)
	}

	// 1. Collect model names used by service functions.
	models := collectModels(input.ServiceFuncs)
	funcs := collectFuncs(input.ServiceFuncs)
	components := collectComponents(input.ServiceFuncs)

	// 2. Transform service files: standalone → struct methods.
	if err := transformServiceFiles(intDir, models, funcs, components, input.ModulePath); err != nil {
		return fmt.Errorf("service transform: %w", err)
	}

	// 3. Generate server.go (Server struct).
	if err := generateServerStruct(intDir, models, funcs, components, input.ModulePath, input.OpenAPIDoc); err != nil {
		return fmt.Errorf("server.go: %w", err)
	}

	// 4. Generate auth.go stub.
	if err := generateAuthStub(intDir); err != nil {
		return fmt.Errorf("auth.go: %w", err)
	}

	// 5. Generate cmd/main.go.
	if err := generateMain(input.ArtifactsDir, models, input.ModulePath); err != nil {
		return fmt.Errorf("main.go: %w", err)
	}

	// 5.5. Generate model implementations (sqlc wrapper).
	if err := generateModelImpls(intDir, models, input.ModulePath, input.SpecsDir, input.ServiceFuncs); err != nil {
		return fmt.Errorf("model impl: %w", err)
	}

	// 6. Generate frontend setup (React + Vite).
	if err := generateFrontendSetup(input.ArtifactsDir, input.OpenAPIDoc, input.STMLDeps, input.STMLPages, input.STMLPageOps); err != nil {
		return fmt.Errorf("frontend setup: %w", err)
	}

	return nil
}

// collectModels extracts unique model names from service functions.
func collectModels(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			if seq.Model != "" {
				parts := strings.SplitN(seq.Model, ".", 2)
				if len(parts) >= 1 {
					seen[parts[0]] = true
				}
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// collectFuncs extracts @func references.
func collectFuncs(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			if seq.Func != "" {
				seen[seq.Func] = true
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// collectComponents extracts @component references.
func collectComponents(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			if seq.Component != "" {
				seen[seq.Component] = true
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// transformServiceFiles reads each .go file in internal/service/,
// converts standalone functions to Server methods, and writes them back in place.
func transformServiceFiles(intDir string, models, funcs, components []string, modulePath string) error {
	serviceDir := filepath.Join(intDir, "service")
	entries, err := os.ReadDir(serviceDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // no service files to transform
		}
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		path := filepath.Join(serviceDir, entry.Name())
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		transformed := transformSource(string(src), models, funcs, components, modulePath)
		if err := os.WriteFile(path, []byte(transformed), 0644); err != nil {
			return err
		}
	}

	return nil
}

// transformSource converts a standalone function source to a Server method.
func transformSource(src string, models, funcs, components []string, modulePath string) string {
	// Add receiver to function declaration.
	src = strings.Replace(src, "\nfunc ", "\nfunc (s *Server) ", 1)

	// Replace model references: courseModel → s.CourseModel
	for _, m := range models {
		varName := lcFirst(m) + "Model"
		fieldName := ucFirst(varName)
		src = strings.ReplaceAll(src, varName+".", "s."+fieldName+".")
	}

	// Replace func references: hashPassword( → s.HashPassword(
	for _, f := range funcs {
		fieldName := ucFirst(f)
		src = strings.ReplaceAll(src, f+"(", "s."+fieldName+"(")
	}

	// Replace component references: notification. → s.Notification.
	for _, c := range components {
		fieldName := ucFirst(c)
		src = strings.ReplaceAll(src, c+".", "s."+fieldName+".")
	}

	// Replace authz and currentUser.
	// ssac generates bare "authz.Check(currentUser, ...)" — authz is not a component.
	src = strings.ReplaceAll(src, "authz.Check(currentUser,", "s.Authz.Check(s.currentUser(r),")
	src = strings.ReplaceAll(src, "currentUser.UserID", "s.currentUser(r).UserID")
	src = strings.ReplaceAll(src, "currentUser.ID", "s.currentUser(r).ID")

	// Qualify model package types used in service code.
	if strings.Contains(src, "QueryOpts{}") {
		src = strings.ReplaceAll(src, "QueryOpts{}", "model.QueryOpts{}")
		// Add model import.
		modelImport := fmt.Sprintf("\"%s/internal/model\"", modulePath)
		if !strings.Contains(src, modelImport) {
			src = strings.Replace(src, "import (", "import (\n\t"+modelImport, 1)
		}
	}

	// Add type assertions for @func results used as string arguments.
	// ssac generates: result, err := s.funcName(args) where result is interface{}.
	// When result is passed to a method expecting string, add .(string).
	for _, f := range funcs {
		// Pattern: s.funcName(...)  → result is interface{}
		// Find variable assignments from func calls and add type assertion where needed.
		callPattern := "s." + ucFirst(f) + "("
		if idx := strings.Index(src, callPattern); idx > 0 {
			// Find the variable name assigned from this call.
			lineStart := strings.LastIndex(src[:idx], "\n") + 1
			assignLine := src[lineStart:idx]
			assignLine = strings.TrimSpace(assignLine)
			// Pattern: "varName, err :="
			if commaIdx := strings.Index(assignLine, ","); commaIdx > 0 {
				varName := strings.TrimSpace(assignLine[:commaIdx])
				if varName != "_" && varName != "" {
					// Add .(string) assertion where this var is used as argument.
					// Only replace when used as a function argument (preceded by comma or paren).
					src = strings.ReplaceAll(src, ", "+varName+",", ", "+varName+".(string),")
					src = strings.ReplaceAll(src, ", "+varName+")", ", "+varName+".(string))")
					src = strings.ReplaceAll(src, "("+varName+",", "("+varName+".(string),")
				}
			}
		}
	}

	return src
}

// lcFirst lowercases the first character.
func lcFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
