package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// scenarioStep represents a single HTTP request in the Hurl scenario.
type scenarioStep struct {
	OperationID string
	Method      string
	Path        string
	Operation   *openapi3.Operation
	PathDepth   int  // number of path segments (for ordering)
	IsAuth      bool // register/login
}

// generateHurlTests generates smoke.hurl from OpenAPI spec.
func generateHurlTests(doc *openapi3.T, outDir string) error {
	if doc == nil || doc.Paths == nil {
		return nil
	}

	testsDir := filepath.Join(outDir, "tests")
	if err := os.MkdirAll(testsDir, 0755); err != nil {
		return fmt.Errorf("create tests dir: %w", err)
	}

	steps := buildScenarioOrder(doc)
	if len(steps) == 0 {
		return nil
	}

	var buf strings.Builder
	buf.WriteString("# Auto-generated by fullend gen — do not edit.\n")
	buf.WriteString("# Run: hurl --test --variable host=http://localhost:8080 smoke.hurl\n\n")

	// Track captured variables for substitution.
	captures := make(map[string]bool)
	hasAuth := hasSecuritySchemes(doc)

	// Write auth preamble if needed.
	if hasAuth {
		writeAuthSection(&buf, doc, captures)
	}

	// Group by resource for section comments.
	currentResource := ""
	for _, step := range steps {
		if step.IsAuth {
			continue // already written
		}

		resource := inferResource(step.Path)
		if resource != currentResource {
			currentResource = resource
			buf.WriteString(fmt.Sprintf("\n# ===== %s =====\n\n", ucFirst(resource)))
		}

		writeStep(&buf, step, captures, doc)
	}

	return os.WriteFile(filepath.Join(testsDir, "smoke.hurl"), []byte(buf.String()), 0644)
}

// buildScenarioOrder sorts endpoints into a dependency-aware execution order.
// Strategy:
//   1. Auth (Register, Login)
//   2. For each resource group: POST (create) → GET → PUT (non-delete)
//   3. Child resource CRUD (recursively)
//   4. DELETE in reverse depth order (children first, then parents)
func buildScenarioOrder(doc *openapi3.T) []scenarioStep {
	var all []scenarioStep

	for path, pi := range doc.Paths.Map() {
		depth := countPathSegments(path)
		for method, op := range pi.Operations() {
			if op == nil {
				continue
			}
			isAuth := isAuthOperation(op.OperationID)
			all = append(all, scenarioStep{
				OperationID: op.OperationID,
				Method:      method,
				Path:        path,
				Operation:   op,
				PathDepth:   depth,
				IsAuth:      isAuth,
			})
		}
	}

	// Separate into categories.
	var authSteps, createSteps, readSteps, updateSteps, deleteSteps []scenarioStep
	for _, s := range all {
		if s.IsAuth {
			authSteps = append(authSteps, s)
			continue
		}
		switch s.Method {
		case "POST":
			createSteps = append(createSteps, s)
		case "GET":
			readSteps = append(readSteps, s)
		case "PUT":
			updateSteps = append(updateSteps, s)
		case "DELETE":
			deleteSteps = append(deleteSteps, s)
		}
	}

	// Sort auth: Register before Login.
	sort.SliceStable(authSteps, func(i, j int) bool {
		return authOrder(authSteps[i].OperationID) < authOrder(authSteps[j].OperationID)
	})

	// Sort creates by depth (parent first), then path.
	sortByDepthPath(createSteps)
	// Sort reads by depth, then path.
	sortByDepthPath(readSteps)
	// Sort updates by depth, then path.
	sortByDepthPath(updateSteps)
	// Sort deletes by depth DESC (children first), then path.
	sort.SliceStable(deleteSteps, func(i, j int) bool {
		if deleteSteps[i].PathDepth != deleteSteps[j].PathDepth {
			return deleteSteps[i].PathDepth > deleteSteps[j].PathDepth
		}
		return deleteSteps[i].Path < deleteSteps[j].Path
	})

	// Final order: auth → create → read → update → delete
	var result []scenarioStep
	result = append(result, authSteps...)
	result = append(result, createSteps...)
	result = append(result, readSteps...)
	result = append(result, updateSteps...)
	result = append(result, deleteSteps...)

	return result
}

func sortByDepthPath(steps []scenarioStep) {
	sort.SliceStable(steps, func(i, j int) bool {
		if steps[i].PathDepth != steps[j].PathDepth {
			return steps[i].PathDepth < steps[j].PathDepth
		}
		return steps[i].Path < steps[j].Path
	})
}

// writeAuthSection writes Register + Login steps.
func writeAuthSection(buf *strings.Builder, doc *openapi3.T, captures map[string]bool) {
	buf.WriteString("# ===== Auth =====\n\n")

	// Find Register and Login operations.
	var registerOp, loginOp *openapi3.Operation
	var registerPath, loginPath string

	for path, pi := range doc.Paths.Map() {
		for _, op := range pi.Operations() {
			if op == nil {
				continue
			}
			switch strings.ToLower(op.OperationID) {
			case "register":
				registerOp = op
				registerPath = path
			case "login":
				loginOp = op
				loginPath = path
			}
		}
	}

	if registerOp != nil {
		buf.WriteString("# Register\n")
		buf.WriteString(fmt.Sprintf("POST {{host}}%s\n", registerPath))
		buf.WriteString("Content-Type: application/json\n")
		reqSchema := getRequestSchema(registerOp)
		body, _ := generateRequestBody(reqSchema)
		buf.WriteString(body + "\n")
		buf.WriteString("\nHTTP 200\n")

		respSchema := getResponseSchema(registerOp)
		asserts := generateResponseAssertions(respSchema, nil)
		if len(asserts) > 0 {
			buf.WriteString("[Asserts]\n")
			for _, a := range asserts {
				buf.WriteString(a + "\n")
			}
		}
		buf.WriteString("\n")
	}

	if loginOp != nil {
		buf.WriteString("# Login\n")
		buf.WriteString(fmt.Sprintf("POST {{host}}%s\n", loginPath))
		buf.WriteString("Content-Type: application/json\n")
		reqSchema := getRequestSchema(loginOp)
		body, _ := generateRequestBody(reqSchema)
		buf.WriteString(body + "\n")
		buf.WriteString("\nHTTP 200\n")
		buf.WriteString("[Captures]\n")
		buf.WriteString("token: jsonpath \"$.token.AccessToken\"\n")
		captures["token"] = true

		buf.WriteString("[Asserts]\n")
		buf.WriteString("jsonpath \"$.token\" exists\n")
		buf.WriteString("\n")
	}
}

// writeStep writes a single endpoint test step.
func writeStep(buf *strings.Builder, step scenarioStep, captures map[string]bool, doc *openapi3.T) {
	op := step.Operation

	buf.WriteString(fmt.Sprintf("# %s\n", step.OperationID))

	// Build URL with path parameter substitution.
	url := substitutePathParams(step.Path, captures)

	// Add query parameters for x- extensions.
	queryParams := buildXQueryParams(op)
	if queryParams != "" {
		url += "?" + queryParams
	}

	buf.WriteString(fmt.Sprintf("%s {{host}}%s\n", step.Method, url))

	// Auth header.
	if needsAuth(op) && captures["token"] {
		buf.WriteString("Authorization: Bearer {{token}}\n")
	}

	// Request body for POST/PUT.
	var sentValues map[string]interface{}
	if step.Method == "POST" || step.Method == "PUT" {
		reqSchema := getRequestSchema(op)
		if reqSchema != nil {
			buf.WriteString("Content-Type: application/json\n")
			var body string
			body, sentValues = generateRequestBody(reqSchema)
			buf.WriteString(body + "\n")
		}
	}

	buf.WriteString("\nHTTP 200\n")

	// Captures: extract ID from POST responses.
	if step.Method == "POST" {
		respSchema := getResponseSchema(op)
		varName, jsonPath := inferCaptureField(respSchema)
		if varName != "" && !captures[varName] {
			buf.WriteString("[Captures]\n")
			buf.WriteString(fmt.Sprintf("%s: jsonpath %q\n", varName, jsonPath))
			captures[varName] = true
		}
	}

	// Assertions.
	respSchema := getResponseSchema(op)
	asserts := generateResponseAssertions(respSchema, sentValues)
	if len(asserts) > 0 {
		buf.WriteString("[Asserts]\n")
		for _, a := range asserts {
			buf.WriteString(a + "\n")
		}
	}

	buf.WriteString("\n")
}

// buildXQueryParams builds query parameters from x- extensions.
func buildXQueryParams(op *openapi3.Operation) string {
	var params []string

	if pag := getExtMap(op, "x-pagination"); pag != nil {
		params = append(params, "limit=2")
	}

	if sortCfg := getExtMap(op, "x-sort"); sortCfg != nil {
		def := getStr(sortCfg, "default", "")
		dir := getStr(sortCfg, "direction", "asc")
		if def != "" {
			params = append(params, "sort="+def)
			params = append(params, "direction="+dir)
		}
	}

	if filterCfg := getExtMap(op, "x-filter"); filterCfg != nil {
		allowed := getStrSlice(filterCfg, "allowed")
		if len(allowed) > 0 {
			params = append(params, allowed[0]+"=test")
		}
	}

	if incCfg := getExtMap(op, "x-include"); incCfg != nil {
		allowed := getStrSlice(incCfg, "allowed")
		var names []string
		for _, spec := range allowed {
			colonIdx := strings.Index(spec, ":")
			if colonIdx > 0 {
				names = append(names, strings.TrimSuffix(spec[:colonIdx], "_id"))
			} else {
				names = append(names, spec)
			}
		}
		if len(names) > 0 {
			params = append(params, "include="+strings.Join(names, ","))
		}
	}

	return strings.Join(params, "&")
}

// substitutePathParams replaces {ParamName} with {{param_name_id}} captured variables.
func substitutePathParams(path string, captures map[string]bool) string {
	var result strings.Builder
	i := 0
	for i < len(path) {
		openBrace := strings.Index(path[i:], "{")
		if openBrace < 0 {
			result.WriteString(path[i:])
			break
		}
		result.WriteString(path[i : i+openBrace])
		closeBrace := strings.Index(path[i+openBrace:], "}")
		if closeBrace < 0 {
			result.WriteString(path[i+openBrace:])
			break
		}
		paramName := path[i+openBrace+1 : i+openBrace+closeBrace]
		varName := pascalToSnakeHurl(paramName)
		result.WriteString("{{" + varName + "}}")
		i = i + openBrace + closeBrace + 1
	}
	return result.String()
}

// pascalToSnakeHurl converts PascalCase to snake_case for Hurl variable names.
func pascalToSnakeHurl(s string) string {
	var result []byte
	for i, c := range s {
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				prev := s[i-1]
				if prev >= 'a' && prev <= 'z' {
					result = append(result, '_')
				} else if prev >= 'A' && prev <= 'Z' && i+1 < len(s) && s[i+1] >= 'a' && s[i+1] <= 'z' {
					result = append(result, '_')
				}
			}
			result = append(result, byte(c-'A'+'a'))
		} else {
			result = append(result, byte(c))
		}
	}
	return string(result)
}

// Helper functions for scenario ordering.

func isAuthOperation(opID string) bool {
	lower := strings.ToLower(opID)
	return lower == "register" || lower == "login"
}

func authOrder(opID string) int {
	if strings.ToLower(opID) == "register" {
		return 0
	}
	return 1
}

func crudOrder(method string) int {
	switch method {
	case "POST":
		return 0
	case "GET":
		return 1
	case "PUT":
		return 2
	case "DELETE":
		return 3
	default:
		return 4
	}
}

func countPathSegments(path string) int {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	return len(parts)
}

func inferResource(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	// Find the first non-parameter segment.
	for _, p := range parts {
		if !strings.HasPrefix(p, "{") {
			return p
		}
	}
	return "other"
}

func hasSecuritySchemes(doc *openapi3.T) bool {
	if doc.Components == nil {
		return false
	}
	return len(doc.Components.SecuritySchemes) > 0
}
