apiVersion: fullend/v1
kind: Project

metadata:
  name: dummy-lesson

backend:
  lang: go
  framework: gin
  module: github.com/geul-org/dummy-lesson
  middleware:
    - bearerAuth
  auth:
    secret_env: JWT_SECRET
    claims:
      ID: user_id
      Email: email
      Role: role

frontend:
  lang: typescript
  framework: react
  bundler: vite
  name: dummy-lesson-web
