// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Gig defines model for Gig.
type Gig struct {
	Budget       *int       `json:"budget,omitempty"`
	ClientId     *int64     `json:"client_id,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Description  *string    `json:"description,omitempty"`
	FreelancerId *int64     `json:"freelancer_id,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	Status       *string    `json:"status,omitempty"`
	Title        *string    `json:"title,omitempty"`
}

// Proposal defines model for Proposal.
type Proposal struct {
	BidAmount    *int    `json:"bid_amount,omitempty"`
	FreelancerId *int64  `json:"freelancer_id,omitempty"`
	GigId        *int64  `json:"gig_id,omitempty"`
	Id           *int64  `json:"id,omitempty"`
	Status       *string `json:"status,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Id    *int64  `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
	Role     string              `json:"role"`
}

// ListGigsParams defines parameters for ListGigs.
type ListGigsParams struct {
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset  *int    `form:"offset,omitempty" json:"offset,omitempty"`
	SortBy  *string `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortDir *string `form:"sortDir,omitempty" json:"sortDir,omitempty"`
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
}

// CreateGigJSONBody defines parameters for CreateGig.
type CreateGigJSONBody struct {
	Budget      int    `json:"budget"`
	Description string `json:"description"`
	Title       string `json:"title"`
}

// SubmitProposalJSONBody defines parameters for SubmitProposal.
type SubmitProposalJSONBody struct {
	BidAmount int `json:"bid_amount"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// CreateGigJSONRequestBody defines body for CreateGig for application/json ContentType.
type CreateGigJSONRequestBody CreateGigJSONBody

// SubmitProposalJSONRequestBody defines body for SubmitProposal for application/json ContentType.
type SubmitProposalJSONRequestBody SubmitProposalJSONBody
