package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/ettle/strcase"
	"github.com/getkin/kin-openapi/openapi3"

	"github.com/geul-org/fullend/internal/policy"
	"github.com/geul-org/fullend/internal/statemachine"
	ssacparser "github.com/geul-org/fullend/internal/ssac/parser"
	ssacvalidator "github.com/geul-org/fullend/internal/ssac/validator"
)

// GlueInput holds everything needed to generate glue code.
type GlueInput struct {
	ArtifactsDir    string
	SpecsDir        string
	ModulePath      string
	OpenAPIDoc      *openapi3.T
	SymbolTable     *ssacvalidator.SymbolTable
	ServiceFuncs    []ssacparser.ServiceFunc
	StateDiagrams   []*statemachine.StateDiagram
	STMLDeps        map[string]string // dependencies from stml generator
	STMLPages       []string          // page names generated by stml
	STMLPageOps     map[string]string // page file name → primary operationID
	Claims          map[string]string // from fullend.yaml backend.auth.claims
	QueueBackend    string            // "postgres", "memory", "" (no queue)
	AuthzPackage    string            // custom authz package, "" = default pkg/authz
	Policies        []*policy.Policy  // parsed OPA Rego policies (for hurl role detection)
}

// internalDir returns the backend/internal/ base path.
func internalDir(artifactsDir string) string {
	return filepath.Join(artifactsDir, "backend", "internal")
}

// Generate creates all glue code files.
func Generate(input *GlueInput) error {
	intDir := internalDir(input.ArtifactsDir)
	if err := os.MkdirAll(intDir, 0755); err != nil {
		return fmt.Errorf("create internal dir: %w", err)
	}

	// Validate: bearerAuth requires claims config.
	if hasBearerScheme(input.OpenAPIDoc) && len(input.Claims) == 0 {
		return fmt.Errorf("OpenAPI has bearerAuth security scheme but fullend.yaml has no claims config")
	}

	models := collectModels(input.ServiceFuncs)


	if hasDomains(input.ServiceFuncs) {
		// Domain mode: per-domain Handler + central Server.
		allFuncs := collectFuncs(input.ServiceFuncs)

		if err := transformServiceFilesWithDomains(intDir, input.ServiceFuncs, models, allFuncs, input.ModulePath, input.OpenAPIDoc); err != nil {
			return fmt.Errorf("service transform (domain): %w", err)
		}
		if err := attachServiceDirectives(intDir, input.ServiceFuncs); err != nil {
			return fmt.Errorf("service directives (domain): %w", err)
		}
		if err := generateAuthStubWithDomains(intDir, input.ModulePath, input.Claims); err != nil {
			return fmt.Errorf("auth (domain): %w", err)
		}
		if len(input.Claims) > 0 {
			if err := generateMiddleware(intDir, input.ModulePath, input.Claims); err != nil {
				return fmt.Errorf("middleware (domain): %w", err)
			}
		}
		if err := generateServerStructWithDomains(intDir, input.ServiceFuncs, input.ModulePath, input.OpenAPIDoc, input.Claims); err != nil {
			return fmt.Errorf("server.go (domain): %w", err)
		}
		if err := generateMainWithDomains(input.ArtifactsDir, input.ServiceFuncs, input.ModulePath, input.QueueBackend, input.Policies); err != nil {
			return fmt.Errorf("main.go (domain): %w", err)
		}
	} else {
		// Flat mode: single Server with all fields (unchanged).
		funcs := collectFuncs(input.ServiceFuncs)

		if err := transformServiceFiles(intDir, models, funcs, input.ModulePath, input.OpenAPIDoc, input.ServiceFuncs); err != nil {
			return fmt.Errorf("service transform: %w", err)
		}
		if err := attachServiceDirectives(intDir, input.ServiceFuncs); err != nil {
			return fmt.Errorf("service directives: %w", err)
		}
		if err := generateServerStruct(intDir, models, funcs, input.ModulePath, input.OpenAPIDoc); err != nil {
			return fmt.Errorf("server.go: %w", err)
		}
		if err := generateAuthStub(intDir); err != nil {
			return fmt.Errorf("auth.go: %w", err)
		}
		if err := generateMain(input.ArtifactsDir, models, input.ModulePath, input.QueueBackend, input.ServiceFuncs, input.Policies); err != nil {
			return fmt.Errorf("main.go: %w", err)
		}
	}

	// Shared: model implementations + frontend (same for both modes).
	modelIncludeSpecs := collectModelIncludes(input.OpenAPIDoc, input.ServiceFuncs)
	cursorSpecs := collectCursorSpecs(input.OpenAPIDoc)
	if err := generateModelImpls(intDir, models, input.ModulePath, input.SpecsDir, input.ServiceFuncs, modelIncludeSpecs, cursorSpecs); err != nil {
		return fmt.Errorf("model impl: %w", err)
	}
	if err := generateFrontendSetup(input.ArtifactsDir, input.OpenAPIDoc, input.STMLDeps, input.STMLPages, input.STMLPageOps); err != nil {
		return fmt.Errorf("frontend setup: %w", err)
	}
	if err := attachTSXDirectives(input.ArtifactsDir); err != nil {
		return fmt.Errorf("tsx directives: %w", err)
	}

	// Hurl smoke test generation.
	if err := generateHurlTests(input.OpenAPIDoc, input.ArtifactsDir, input.SpecsDir, input.StateDiagrams, input.ServiceFuncs, input.Policies); err != nil {
		return fmt.Errorf("hurl-gen: %w", err)
	}

	return nil
}

// collectModels extracts unique model names from service functions.
func collectModels(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			// Skip @call — package-level funcs are not models.
			if seq.Type == "call" {
				continue
			}
			if seq.Model != "" {
				parts := strings.SplitN(seq.Model, ".", 2)
				if len(parts) >= 1 {
					seen[parts[0]] = true
				}
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// collectFuncs extracts @call references without a package prefix.
// Package-level funcs (e.g. "auth.VerifyPassword") are called directly via import, not via Handler fields.
func collectFuncs(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			if seq.Type == "call" && seq.Model != "" {
				if !strings.Contains(seq.Model, ".") {
					seen[seq.Model] = true
				}
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// transformServiceFiles reads each .go file in internal/service/,
// converts standalone functions to Server methods, and writes them back in place.
func transformServiceFiles(intDir string, models, funcs []string, modulePath string, doc *openapi3.T, serviceFuncs []ssacparser.ServiceFunc) error {
	serviceDir := filepath.Join(intDir, "service")
	entries, err := os.ReadDir(serviceDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // no service files to transform
		}
		return err
	}

	// Build filename → operationID mapping from SSaC service funcs.
	fileToOpID := buildFileToOperationID(serviceFuncs)

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		path := filepath.Join(serviceDir, entry.Name())
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		opID := fileToOpID[entry.Name()]
		transformed := transformSource(string(src), models, funcs, modulePath, false, doc, opID)
		if err := os.WriteFile(path, []byte(transformed), 0644); err != nil {
			return err
		}
	}

	return nil
}

// transformSource converts a standalone function source to a struct method.
// isDomain: false → (s *Server) receiver, true → (h *Handler) receiver.
// doc + operationID: used to replace __RESPONSE_STATUS__ with OpenAPI success code.
func transformSource(src string, models, funcs []string, modulePath string, isDomain bool, doc *openapi3.T, operationID string) string {
	rcv := "s"
	rcvType := "*Server"
	if isDomain {
		rcv = "h"
		rcvType = "*Handler"
	}

	// Add receiver to function declaration (skip if already has one).
	if idx := strings.Index(src, "\nfunc "); idx >= 0 {
		after := src[idx+len("\nfunc "):]
		if len(after) == 0 || after[0] != '(' {
			src = strings.Replace(src, "\nfunc ", "\nfunc ("+rcv+" "+rcvType+") ", 1)
		}
	}

	// Replace model references: courseModel → {rcv}.CourseModel
	for _, m := range models {
		varName := lcFirst(m) + "Model"
		fieldName := ucFirst(varName)
		src = strings.ReplaceAll(src, varName+".", rcv+"."+fieldName+".")
	}

	// Replace func references: hashPassword( → {rcv}.HashPassword(
	for _, f := range funcs {
		fieldName := ucFirst(f)
		src = strings.ReplaceAll(src, f+"(", rcv+"."+fieldName+"(")
	}

	// Add model import when model package types are used (QueryOpts, ParseQueryOpts, CurrentUser, etc.)
	needsModel := strings.Contains(src, "model.QueryOpts") || strings.Contains(src, "model.ParseQueryOpts") || strings.Contains(src, "*model.CurrentUser")
	if needsModel {
		modelImport := fmt.Sprintf("\"%s/internal/model\"", modulePath)
		if !strings.Contains(src, modelImport) {
			src = strings.Replace(src, "import (", "import (\n\t"+modelImport, 1)
		}
	}

	// Fix state machine imports: "states/XXXstate" → "{modulePath}/internal/states/XXXstate"
	if strings.Contains(src, "\"states/") {
		src = strings.ReplaceAll(src, "\"states/", fmt.Sprintf("\"%s/internal/states/", modulePath))
	}

	// Fix authz import: "authz" → "github.com/geul-org/fullend/pkg/authz"
	if strings.Contains(src, "\t\"authz\"\n") {
		src = strings.ReplaceAll(src, "\t\"authz\"\n", "\t\"github.com/geul-org/fullend/pkg/authz\"\n")
	}

	// Fix queue import: "queue" → "github.com/geul-org/fullend/pkg/queue"
	if strings.Contains(src, "\t\"queue\"\n") {
		src = strings.ReplaceAll(src, "\t\"queue\"\n", "\t\"github.com/geul-org/fullend/pkg/queue\"\n")
	}

	// Fix config import: "config" → "github.com/geul-org/fullend/pkg/config"
	if strings.Contains(src, "\t\"config\"\n") {
		src = strings.ReplaceAll(src, "\t\"config\"\n", "\t\"github.com/geul-org/fullend/pkg/config\"\n")
	}

	// Remove bare "model" import (already added as full path above)
	if strings.Contains(src, "\t\"model\"\n") {
		src = strings.ReplaceAll(src, "\t\"model\"\n", "")
	}

	// Add type assertions for @func results used as string arguments.
	for _, f := range funcs {
		callPattern := rcv + "." + ucFirst(f) + "("
		if idx := strings.Index(src, callPattern); idx > 0 {
			lineStart := strings.LastIndex(src[:idx], "\n") + 1
			assignLine := src[lineStart:idx]
			assignLine = strings.TrimSpace(assignLine)
			if commaIdx := strings.Index(assignLine, ","); commaIdx > 0 {
				varName := strings.TrimSpace(assignLine[:commaIdx])
				if varName != "_" && varName != "" {
					src = strings.ReplaceAll(src, ", "+varName+",", ", "+varName+".(string),")
					src = strings.ReplaceAll(src, ", "+varName+")", ", "+varName+".(string))")
					src = strings.ReplaceAll(src, "("+varName+",", "("+varName+".(string),")
				}
			}
		}
	}

	// Replace __RESPONSE_STATUS__ with OpenAPI success code.
	if strings.Contains(src, "__RESPONSE_STATUS__") && doc != nil && operationID != "" {
		statusConst := resolveSuccessStatus(doc, operationID)
		if statusConst != "" {
			if statusConst == "http.StatusNoContent" {
				// 204: replace entire c.JSON(__RESPONSE_STATUS__, ...) with c.Status(http.StatusNoContent)
				re := regexp.MustCompile(`c\.JSON\(__RESPONSE_STATUS__,\s*[^)]+\)`)
				src = re.ReplaceAllString(src, "c.Status(http.StatusNoContent)")
			} else {
				src = strings.ReplaceAll(src, "__RESPONSE_STATUS__", statusConst)
			}
		}
	}

	return src
}

// getExtMap extracts a map extension value from an OpenAPI operation.
func getExtMap(op *openapi3.Operation, key string) map[string]interface{} {
	if op.Extensions == nil {
		return nil
	}
	v, ok := op.Extensions[key]
	if !ok {
		return nil
	}
	m, ok := v.(map[string]interface{})
	if ok {
		return m
	}
	return nil
}

// getStr extracts a string value from a map with a default.
func getStr(m map[string]interface{}, key, def string) string {
	v, ok := m[key]
	if !ok {
		return def
	}
	s, ok := v.(string)
	if ok {
		return s
	}
	return def
}

// getStrSlice extracts a string slice from a map.
func getStrSlice(m map[string]interface{}, key string) []string {
	v, ok := m[key]
	if !ok {
		return nil
	}
	arr, ok := v.([]interface{})
	if !ok {
		return nil
	}
	var result []string
	for _, item := range arr {
		if s, ok := item.(string); ok {
			result = append(result, s)
		}
	}
	return result
}

// hasBearerScheme checks if the OpenAPI doc has a bearerAuth security scheme.
func hasBearerScheme(doc *openapi3.T) bool {
	if doc == nil || doc.Components == nil || doc.Components.SecuritySchemes == nil {
		return false
	}
	for _, ref := range doc.Components.SecuritySchemes {
		if ref.Value != nil && ref.Value.Type == "http" && ref.Value.Scheme == "bearer" {
			return true
		}
	}
	return false
}

// hasDomains returns true if any service function has a non-empty Domain.
func hasDomains(funcs []ssacparser.ServiceFunc) bool {
	for _, f := range funcs {
		if f.Domain != "" {
			return true
		}
	}
	return false
}

// uniqueDomains returns sorted unique non-empty domain names.
func uniqueDomains(funcs []ssacparser.ServiceFunc) []string {
	seen := make(map[string]bool)
	for _, f := range funcs {
		if f.Domain != "" {
			seen[f.Domain] = true
		}
	}
	var result []string
	for d := range seen {
		result = append(result, d)
	}
	sort.Strings(result)
	return result
}

// collectModelsForDomain extracts model names used by funcs in a specific domain.
func collectModelsForDomain(funcs []ssacparser.ServiceFunc, domain string) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		if fn.Domain != domain {
			continue
		}
		for _, seq := range fn.Sequences {
			// Skip @call — package-level funcs are not models.
			if seq.Type == "call" {
				continue
			}
			if seq.Model != "" {
				parts := strings.SplitN(seq.Model, ".", 2)
				if len(parts) >= 1 {
					seen[parts[0]] = true
				}
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// collectFuncsForDomain extracts @call references (without package prefix) for a specific domain.
func collectFuncsForDomain(funcs []ssacparser.ServiceFunc, domain string) []string {
	seen := make(map[string]bool)
	for _, fn := range funcs {
		if fn.Domain != domain {
			continue
		}
		for _, seq := range fn.Sequences {
			if seq.Type == "call" && seq.Model != "" {
				if !strings.Contains(seq.Model, ".") {
					seen[seq.Model] = true
				}
			}
		}
	}
	var result []string
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

// domainNeedsAuth returns true if any func in the domain uses authz or currentUser.
func domainNeedsAuth(funcs []ssacparser.ServiceFunc, domain string) bool {
	for _, fn := range funcs {
		if fn.Domain != domain {
			continue
		}
		for _, seq := range fn.Sequences {
			if seq.Type == "auth" {
				return true
			}
			// Check if any arg references currentUser.
			for _, arg := range seq.Args {
				if arg.Source == "currentUser" {
					return true
				}
			}
		}
	}
	return false
}

// lcFirst converts to camelCase (lowercases the first character with Go initialism handling).
func lcFirst(s string) string {
	return strcase.ToGoCamel(s)
}

// resolveSuccessStatus finds the 2xx success response code for an operationId in OpenAPI
// and returns the corresponding Go http.Status constant. Returns "" if not found.
func resolveSuccessStatus(doc *openapi3.T, operationID string) string {
	if doc == nil || doc.Paths == nil {
		return ""
	}
	for _, pi := range doc.Paths.Map() {
		for _, op := range pi.Operations() {
			if op.OperationID != operationID {
				continue
			}
			if op.Responses == nil {
				return ""
			}
			for code := range op.Responses.Map() {
				if len(code) == 3 && code[0] == '2' {
					return httpStatusConst(code)
				}
			}
			return ""
		}
	}
	return ""
}

// httpStatusConst converts a numeric HTTP status code string to Go's net/http constant name.
func httpStatusConst(code string) string {
	switch code {
	case "200":
		return "http.StatusOK"
	case "201":
		return "http.StatusCreated"
	case "204":
		return "http.StatusNoContent"
	default:
		return "http.StatusOK"
	}
}

// buildFileToOperationID builds a map from generated .go filename to operationID.
// SSaC parser sets FileName to the .ssac basename (e.g. "create_gig.ssac"),
// so we convert to .go extension for lookup by the generated file.
func buildFileToOperationID(funcs []ssacparser.ServiceFunc) map[string]string {
	result := make(map[string]string)
	for _, fn := range funcs {
		key := strings.TrimSuffix(fn.FileName, ".ssac") + ".go"
		result[key] = fn.Name
	}
	return result
}

// collectModelIncludes extracts per-model x-include specs from OpenAPI operations.
// Maps operationId → model via serviceFuncs, then merges all include specs per model.
// Returns map[ModelName][]string where values are raw include specs (e.g. "user", "instructor_id:user").
func collectModelIncludes(doc *openapi3.T, funcs []ssacparser.ServiceFunc) map[string][]string {
	// Map operationId → model name (from the first get sequence with @model).
	opToModel := make(map[string]string)
	for _, fn := range funcs {
		for _, seq := range fn.Sequences {
			if seq.Model != "" && seq.Type == "get" {
				parts := strings.SplitN(seq.Model, ".", 2)
				if len(parts) >= 1 {
					opToModel[fn.Name] = parts[0]
					break
				}
			}
		}
	}

	result := make(map[string][]string)
	if doc == nil || doc.Paths == nil {
		return result
	}

	for _, pathItem := range doc.Paths.Map() {
		for _, op := range pathItem.Operations() {
			if op.OperationID == "" {
				continue
			}
			incCfg := getExtMap(op, "x-include")
			if incCfg == nil {
				continue
			}
			allowed := getStrSlice(incCfg, "allowed")
			if len(allowed) == 0 {
				continue
			}
			modelName, ok := opToModel[op.OperationID]
			if !ok {
				continue
			}
			existing := result[modelName]
			for _, spec := range allowed {
				found := false
				for _, e := range existing {
					if e == spec {
						found = true
						break
					}
				}
				if !found {
					existing = append(existing, spec)
				}
			}
			result[modelName] = existing
		}
	}

	return result
}

// collectCursorSpecs extracts cursor column Go field name per operationId.
// Returns map[operationId]string ("ID" default, or PascalCase of x-sort.default).
func collectCursorSpecs(doc *openapi3.T) map[string]string {
	result := make(map[string]string)
	if doc == nil || doc.Paths == nil {
		return result
	}
	for _, pi := range doc.Paths.Map() {
		for _, op := range pi.Operations() {
			if op == nil || op.OperationID == "" {
				continue
			}
			pag := getExtMap(op, "x-pagination")
			if pag == nil || getStr(pag, "style", "") != "cursor" {
				continue
			}
			cursorField := "ID"
			if sortExt := getExtMap(op, "x-sort"); sortExt != nil {
				if def := getStr(sortExt, "default", ""); def != "" {
					cursorField = strcase.ToGoPascal(def)
				}
			}
			result[op.OperationID] = cursorField
		}
	}
	return result
}
