package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ettle/strcase"
	"github.com/getkin/kin-openapi/openapi3"

	"github.com/geul-org/fullend/internal/statemachine"
	ssacparser "github.com/geul-org/ssac/parser"
)

// scenarioStep represents a single HTTP request in the Hurl scenario.
type scenarioStep struct {
	OperationID string
	Method      string
	Path        string
	Operation   *openapi3.Operation
	PathDepth   int  // number of path segments (for ordering)
	IsAuth      bool // register/login
}

// generateHurlTests generates smoke.hurl from OpenAPI spec.
func generateHurlTests(doc *openapi3.T, outDir, specsDir string, diagrams []*statemachine.StateDiagram, serviceFuncs []ssacparser.ServiceFunc) error {
	if doc == nil || doc.Paths == nil {
		return nil
	}

	testsDir := filepath.Join(outDir, "tests")
	if err := os.MkdirAll(testsDir, 0755); err != nil {
		return fmt.Errorf("create tests dir: %w", err)
	}

	steps := buildScenarioOrder(doc, specsDir, diagrams, serviceFuncs)
	if len(steps) == 0 {
		return nil
	}

	var buf strings.Builder
	buf.WriteString("# Auto-generated by fullend gen — do not edit.\n")
	buf.WriteString("# Run: hurl --test --variable host=http://localhost:8080 smoke.hurl\n\n")

	// Track captured variables for substitution.
	captures := make(map[string]bool)
	hasAuth := hasSecuritySchemes(doc)

	// Write auth preamble if needed.
	if hasAuth {
		writeAuthSection(&buf, doc, captures)
	}

	// Group by resource for section comments.
	currentResource := ""
	for _, step := range steps {
		if step.IsAuth {
			continue // already written
		}

		resource := inferResource(step.Path)
		if resource != currentResource {
			currentResource = resource
			buf.WriteString(fmt.Sprintf("\n# ===== %s =====\n\n", strcase.ToGoPascal(resource)))
		}

		writeStep(&buf, step, captures, doc)
	}

	return os.WriteFile(filepath.Join(testsDir, "smoke.hurl"), []byte(buf.String()), 0644)
}

// buildScenarioOrder sorts endpoints into a dependency-aware execution order.
// Strategy:
//  1. Auth (Register, Login)
//  2. Interleaved creates + state transitions:
//     - Top-level creates first (depth ≤ 2)
//     - State transitions in stateDiagram BFS order
//     - Nested creates (depth > 2) after parent resource's first transition
//  3. Updates (PUT without @state)
//  4. Read (GET) last
//  5. DELETE in FK dependency order
func buildScenarioOrder(doc *openapi3.T, specsDir string, diagrams []*statemachine.StateDiagram, serviceFuncs []ssacparser.ServiceFunc) []scenarioStep {
	var all []scenarioStep

	for path, pi := range doc.Paths.Map() {
		depth := countPathSegments(path)
		for method, op := range pi.Operations() {
			if op == nil {
				continue
			}
			isAuth := isAuthOperation(op.OperationID)
			all = append(all, scenarioStep{
				OperationID: op.OperationID,
				Method:      method,
				Path:        path,
				Operation:   op,
				PathDepth:   depth,
				IsAuth:      isAuth,
			})
		}
	}

	// Build set of operationIDs that have @state in SSaC.
	stateOps := buildStateOpsSet(serviceFuncs)

	// Build transition order from stateDiagrams: event → order index.
	transitionOrder := buildTransitionOrder(diagrams)

	// Build resource → first transition order (for nested create placement).
	resourceFirstTransition := buildResourceFirstTransition(diagrams, transitionOrder)

	// Assign a sort key to each non-auth, non-read, non-delete step.
	type orderedStep struct {
		step  scenarioStep
		order float64
	}

	var authSteps []scenarioStep
	var midSteps []orderedStep
	var readSteps, deleteSteps []scenarioStep

	for _, s := range all {
		if s.IsAuth {
			authSteps = append(authSteps, s)
			continue
		}
		switch s.Method {
		case "GET":
			readSteps = append(readSteps, s)
		case "DELETE":
			deleteSteps = append(deleteSteps, s)
		default:
			if stateOps[s.OperationID] {
				// State transition: use diagram BFS order.
				midSteps = append(midSteps, orderedStep{s, float64(transitionOrder[s.OperationID])})
			} else if s.Method == "POST" {
				parentResource := findParentResource(s.Path)
				if parentResource == "" {
					// Top-level create: before all transitions.
					midSteps = append(midSteps, orderedStep{s, -1.0})
				} else if firstOrd, ok := resourceFirstTransition[parentResource]; ok {
					// Nested create: after parent's first transition.
					midSteps = append(midSteps, orderedStep{s, float64(firstOrd) + 0.5})
				} else {
					midSteps = append(midSteps, orderedStep{s, -0.5})
				}
			} else {
				// PUT/PATCH without @state: after transitions.
				midSteps = append(midSteps, orderedStep{s, 900.0})
			}
		}
	}

	// Sort auth: Register before Login.
	sort.SliceStable(authSteps, func(i, j int) bool {
		return authOrder(authSteps[i].OperationID) < authOrder(authSteps[j].OperationID)
	})

	// Sort mid steps by order, then depth, then path for stability.
	sort.SliceStable(midSteps, func(i, j int) bool {
		if midSteps[i].order != midSteps[j].order {
			return midSteps[i].order < midSteps[j].order
		}
		if midSteps[i].step.PathDepth != midSteps[j].step.PathDepth {
			return midSteps[i].step.PathDepth < midSteps[j].step.PathDepth
		}
		return midSteps[i].step.Path < midSteps[j].step.Path
	})

	// Sort reads by depth, then path.
	sortByDepthPath(readSteps)
	// Sort deletes by FK dependency.
	deleteSteps = sortDeletesByFK(deleteSteps, specsDir)

	// Final order: auth → mid (creates + transitions interleaved) → read → delete
	var result []scenarioStep
	result = append(result, authSteps...)
	for _, ms := range midSteps {
		result = append(result, ms.step)
	}
	result = append(result, readSteps...)
	result = append(result, deleteSteps...)

	return result
}

// findParentResource extracts the parent resource from a nested path.
// e.g. /gigs/{GigID}/proposals → "gigs", /gigs → "".
func findParentResource(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	for i := 1; i < len(parts); i++ {
		if strings.HasPrefix(parts[i], "{") && i > 0 {
			// Found a path param; the segment before it is a resource.
			// If there's more path after this param, parts[i-1] is the parent.
			if i+1 < len(parts) {
				return parts[i-1]
			}
		}
	}
	return ""
}

// buildResourceFirstTransition maps plural resource name → first transition order index.
func buildResourceFirstTransition(diagrams []*statemachine.StateDiagram, transitionOrder map[string]int) map[string]int {
	result := make(map[string]int)
	for _, d := range diagrams {
		// Pluralize diagram ID: "gig" → "gigs".
		resource := d.ID + "s"
		for _, t := range d.Transitions {
			if t.From == d.InitialState {
				if ord, ok := transitionOrder[t.Event]; ok {
					if existing, exists := result[resource]; !exists || ord < existing {
						result[resource] = ord
					}
				}
			}
		}
	}
	return result
}

// buildStateOpsSet returns operationIDs that have @state annotations in SSaC.
func buildStateOpsSet(serviceFuncs []ssacparser.ServiceFunc) map[string]bool {
	ops := make(map[string]bool)
	for _, sf := range serviceFuncs {
		for _, seq := range sf.Sequences {
			if seq.Type == ssacparser.SeqState {
				ops[sf.Name] = true
				break
			}
		}
	}
	return ops
}

// buildTransitionOrder walks stateDiagrams BFS from initial state,
// returning event → order index for sorting.
func buildTransitionOrder(diagrams []*statemachine.StateDiagram) map[string]int {
	order := make(map[string]int)
	idx := 0
	for _, d := range diagrams {
		// BFS from initial state following transitions.
		visited := make(map[string]bool)
		queue := []string{d.InitialState}
		visited[d.InitialState] = true
		for len(queue) > 0 {
			state := queue[0]
			queue = queue[1:]
			for _, t := range d.Transitions {
				if t.From == state && !visited[t.To] {
					if _, exists := order[t.Event]; !exists {
						order[t.Event] = idx
						idx++
					}
					visited[t.To] = true
					queue = append(queue, t.To)
				}
			}
		}
	}
	return order
}

func sortByDepthPath(steps []scenarioStep) {
	sort.SliceStable(steps, func(i, j int) bool {
		if steps[i].PathDepth != steps[j].PathDepth {
			return steps[i].PathDepth < steps[j].PathDepth
		}
		return steps[i].Path < steps[j].Path
	})
}

// writeAuthSection writes Register + Login steps.
func writeAuthSection(buf *strings.Builder, doc *openapi3.T, captures map[string]bool) {
	buf.WriteString("# ===== Auth =====\n\n")

	// Find Register and Login operations.
	var registerOp, loginOp *openapi3.Operation
	var registerPath, loginPath string

	for path, pi := range doc.Paths.Map() {
		for _, op := range pi.Operations() {
			if op == nil {
				continue
			}
			switch strings.ToLower(op.OperationID) {
			case "register":
				registerOp = op
				registerPath = path
			case "login":
				loginOp = op
				loginPath = path
			}
		}
	}

	if registerOp != nil {
		buf.WriteString("# Register\n")
		buf.WriteString(fmt.Sprintf("POST {{host}}%s\n", registerPath))
		buf.WriteString("Content-Type: application/json\n")
		reqSchema := getRequestSchema(registerOp)
		body, _ := generateRequestBody(reqSchema)
		buf.WriteString(body + "\n")
		buf.WriteString("\nHTTP 200\n")

		respSchema := getResponseSchema(registerOp)
		asserts := generateResponseAssertions(respSchema, nil)
		if len(asserts) > 0 {
			buf.WriteString("[Asserts]\n")
			for _, a := range asserts {
				buf.WriteString(a + "\n")
			}
		}
		buf.WriteString("\n")
	}

	if loginOp != nil {
		buf.WriteString("# Login\n")
		buf.WriteString(fmt.Sprintf("POST {{host}}%s\n", loginPath))
		buf.WriteString("Content-Type: application/json\n")
		reqSchema := getRequestSchema(loginOp)
		body, _ := generateRequestBody(reqSchema)
		buf.WriteString(body + "\n")
		buf.WriteString("\nHTTP 200\n")

		// Find token field name from response schema.
		tokenField := "token"
		if respSchema := getResponseSchema(loginOp); respSchema != nil && respSchema.Properties != nil {
			for name := range respSchema.Properties {
				lname := strings.ToLower(name)
				if strings.Contains(lname, "token") || strings.Contains(lname, "accesstoken") {
					tokenField = name
					break
				}
			}
		}

		buf.WriteString("[Captures]\n")
		buf.WriteString(fmt.Sprintf("token: jsonpath \"$.%s\"\n", tokenField))
		captures["token"] = true

		buf.WriteString("[Asserts]\n")
		buf.WriteString(fmt.Sprintf("jsonpath \"$.%s\" exists\n", tokenField))
		buf.WriteString("\n")
	}
}

// writeStep writes a single endpoint test step.
func writeStep(buf *strings.Builder, step scenarioStep, captures map[string]bool, doc *openapi3.T) {
	op := step.Operation

	buf.WriteString(fmt.Sprintf("# %s\n", step.OperationID))

	// Build URL with path parameter substitution.
	url := substitutePathParams(step.Path, captures)

	// Add query parameters for x- extensions.
	queryParams := buildXQueryParams(op)
	if queryParams != "" {
		url += "?" + queryParams
	}

	buf.WriteString(fmt.Sprintf("%s {{host}}%s\n", step.Method, url))

	// Auth header.
	if needsAuth(op) && captures["token"] {
		buf.WriteString("Authorization: Bearer {{token}}\n")
	}

	// Request body for POST/PUT.
	var sentValues map[string]interface{}
	if step.Method == "POST" || step.Method == "PUT" {
		reqSchema := getRequestSchema(op)
		if reqSchema != nil {
			buf.WriteString("Content-Type: application/json\n")
			var body string
			body, sentValues = generateRequestBody(reqSchema)
			buf.WriteString(body + "\n")
		}
	}

	buf.WriteString("\nHTTP 200\n")

	// Captures: extract ID from POST responses.
	if step.Method == "POST" {
		respSchema := getResponseSchema(op)
		varName, jsonPath := inferCaptureField(respSchema)
		if varName != "" && !captures[varName] {
			buf.WriteString("[Captures]\n")
			buf.WriteString(fmt.Sprintf("%s: jsonpath %q\n", varName, jsonPath))
			captures[varName] = true
		}
	}

	// Assertions.
	respSchema := getResponseSchema(op)
	asserts := generateResponseAssertions(respSchema, sentValues)
	if len(asserts) > 0 {
		buf.WriteString("[Asserts]\n")
		for _, a := range asserts {
			buf.WriteString(a + "\n")
		}
	}

	buf.WriteString("\n")
}

// buildXQueryParams builds query parameters from x- extensions.
func buildXQueryParams(op *openapi3.Operation) string {
	var params []string

	if pag := getExtMap(op, "x-pagination"); pag != nil {
		params = append(params, "limit=2")
	}

	if sortCfg := getExtMap(op, "x-sort"); sortCfg != nil {
		def := getStr(sortCfg, "default", "")
		dir := getStr(sortCfg, "direction", "asc")
		if def != "" {
			params = append(params, "sort="+def)
			params = append(params, "direction="+dir)
		}
	}

	if filterCfg := getExtMap(op, "x-filter"); filterCfg != nil {
		allowed := getStrSlice(filterCfg, "allowed")
		if len(allowed) > 0 {
			params = append(params, allowed[0]+"=test_string")
		}
	}

	// x-include is codegen metadata only — no runtime query parameter.

	return strings.Join(params, "&")
}

// substitutePathParams replaces {ParamName} with {{captured_var}} using captured variables.
// For {ID}, it looks at the preceding path segment to find the matching capture (e.g. /gigs/{ID} → gig_id).
func substitutePathParams(path string, captures map[string]bool) string {
	segments := strings.Split(path, "/")
	for i, seg := range segments {
		if !strings.HasPrefix(seg, "{") || !strings.HasSuffix(seg, "}") {
			continue
		}
		paramName := seg[1 : len(seg)-1]
		snakeParam := pascalToSnakeHurl(paramName)

		// First, check if the plain snake param exists in captures.
		if captures[snakeParam] {
			segments[i] = "{{" + snakeParam + "}}"
			continue
		}

		// Derive from preceding segment: /gigs/{ID} → gig_id.
		if i > 0 {
			resource := segments[i-1]
			singular := strings.TrimSuffix(resource, "s")
			derivedVar := singular + "_" + snakeParam
			if captures[derivedVar] {
				segments[i] = "{{" + derivedVar + "}}"
				continue
			}
		}

		// Fallback: use plain snake param.
		segments[i] = "{{" + snakeParam + "}}"
	}
	return strings.Join(segments, "/")
}

// pascalToSnakeHurl converts PascalCase to snake_case for Hurl variable names.
func pascalToSnakeHurl(s string) string {
	return strcase.ToSnake(s)
}

// Helper functions for scenario ordering.

func isAuthOperation(opID string) bool {
	lower := strings.ToLower(opID)
	return lower == "register" || lower == "login"
}

func authOrder(opID string) int {
	if strings.ToLower(opID) == "register" {
		return 0
	}
	return 1
}

func crudOrder(method string) int {
	switch method {
	case "POST":
		return 0
	case "GET":
		return 1
	case "PUT":
		return 2
	case "DELETE":
		return 3
	default:
		return 4
	}
}

func countPathSegments(path string) int {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	return len(parts)
}

func inferResource(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	// Find the first non-parameter segment.
	for _, p := range parts {
		if !strings.HasPrefix(p, "{") {
			return p
		}
	}
	return "other"
}

func hasSecuritySchemes(doc *openapi3.T) bool {
	if doc.Components == nil {
		return false
	}
	return len(doc.Components.SecuritySchemes) > 0
}

// sortDeletesByFK sorts DELETE steps using DDL FK dependency graph.
// Children (tables with FK references) are deleted before parents.
func sortDeletesByFK(steps []scenarioStep, specsDir string) []scenarioStep {
	if len(steps) <= 1 || specsDir == "" {
		return steps
	}

	// Parse DDL to get FK relationships.
	tables := parseDDLFiles(specsDir)

	// Build dependency graph: table → set of tables it depends on (via FK).
	// e.g. lessons depends on courses (lessons.course_id → courses)
	deps := make(map[string]map[string]bool)
	for _, t := range tables {
		for _, col := range t.Columns {
			if col.FKTable != "" {
				if deps[t.TableName] == nil {
					deps[t.TableName] = make(map[string]bool)
				}
				deps[t.TableName][col.FKTable] = true
			}
		}
	}

	// Topological sort: tables with no dependents first, then their parents.
	// For DELETE order: children (FK holders) before parents.
	order := topoSortDelete(deps)

	// Map path → table name for each DELETE step.
	tableOrder := make(map[string]int)
	for i, t := range order {
		tableOrder[t] = i
	}

	// Collect which tables have DELETE endpoints.
	deletableTables := make(map[string]bool)
	for _, s := range steps {
		t := inferTableFromPath(s.Path)
		if t != "" {
			deletableTables[t] = true
		}
	}

	// Build reverse deps: parent → children that reference it.
	reverseDeps := make(map[string][]string)
	for child, parents := range deps {
		for parent := range parents {
			reverseDeps[parent] = append(reverseDeps[parent], child)
		}
	}

	// Filter out steps whose table has undeletable children (FK references with no DELETE endpoint).
	var filteredSteps []scenarioStep
	for _, s := range steps {
		t := inferTableFromPath(s.Path)
		if canDeleteTable(t, deletableTables, reverseDeps) {
			filteredSteps = append(filteredSteps, s)
		}
	}
	steps = filteredSteps

	// Sort steps by topological order.
	sort.SliceStable(steps, func(i, j int) bool {
		ti := inferTableFromPath(steps[i].Path)
		tj := inferTableFromPath(steps[j].Path)
		oi, oki := tableOrder[ti]
		oj, okj := tableOrder[tj]
		if oki && okj {
			return oi < oj
		}
		// Fallback: depth DESC, then path.
		if steps[i].PathDepth != steps[j].PathDepth {
			return steps[i].PathDepth > steps[j].PathDepth
		}
		return steps[i].Path < steps[j].Path
	})

	return steps
}

// topoSortDelete returns tables in deletion order (children before parents).
func topoSortDelete(deps map[string]map[string]bool) []string {
	// Collect all tables.
	allTables := make(map[string]bool)
	for t := range deps {
		allTables[t] = true
		for dep := range deps[t] {
			allTables[dep] = true
		}
	}

	// Count how many tables depend on each table (in-degree as parent).
	childCount := make(map[string]int)
	for _, parents := range deps {
		for p := range parents {
			childCount[p]++
		}
	}

	// Start with leaf tables (no children depending on them).
	var queue []string
	for t := range allTables {
		if childCount[t] == 0 {
			queue = append(queue, t)
		}
	}
	sort.Strings(queue)

	var result []string
	visited := make(map[string]bool)

	for len(queue) > 0 {
		t := queue[0]
		queue = queue[1:]
		if visited[t] {
			continue
		}
		visited[t] = true
		result = append(result, t)

		// Decrement child count for parents of this table.
		for parent := range deps[t] {
			childCount[parent]--
			if childCount[parent] == 0 {
				queue = append(queue, parent)
				sort.Strings(queue)
			}
		}
	}

	// Add any remaining (circular deps — shouldn't happen).
	for t := range allTables {
		if !visited[t] {
			result = append(result, t)
		}
	}

	return result
}

// canDeleteTable returns true if a table can be safely deleted in smoke tests.
// A table is deletable only if all child tables (that reference it via FK) also have DELETE endpoints.
func canDeleteTable(table string, deletableTables map[string]bool, reverseDeps map[string][]string) bool {
	children := reverseDeps[table]
	for _, child := range children {
		if !deletableTables[child] {
			return false
		}
		// Recursively check: the child must also be deletable.
		if !canDeleteTable(child, deletableTables, reverseDeps) {
			return false
		}
	}
	return true
}

// inferTableFromPath extracts the plural table name from a URL path.
// e.g. "/courses/{CourseID}" → "courses", "/lessons/{LessonID}" → "lessons"
func inferTableFromPath(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	// Find the first non-parameter segment.
	for _, p := range parts {
		if !strings.HasPrefix(p, "{") && !strings.HasPrefix(p, ":") {
			return p
		}
	}
	return ""
}
