package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/geul-org/fullend/internal/contract"
	"github.com/geul-org/fullend/internal/statemachine"
)

// GenerateStateMachines generates Go state machine packages from stateDiagrams.
// Output: <artifactsDir>/backend/internal/states/<id>state/<id>state.go
func GenerateStateMachines(diagrams []*statemachine.StateDiagram, artifactsDir, modulePath string) error {
	if len(diagrams) == 0 {
		return nil
	}

	statesBaseDir := filepath.Join(artifactsDir, "backend", "internal", "states")

	for _, d := range diagrams {
		pkgName := d.ID + "state"
		pkgDir := filepath.Join(statesBaseDir, pkgName)
		if err := os.MkdirAll(pkgDir, 0755); err != nil {
			return fmt.Errorf("create states dir for %s: %w", d.ID, err)
		}

		src := generateStateMachineSource(d, pkgName)

		// Inject file-level //fullend:gen directive.
		dir := &contract.Directive{
			Ownership: "gen",
			SSOT:      "states/" + d.ID + ".md",
			Contract:  contract.HashStateDiagram(d),
		}
		src = injectFileDirective(src, dir)

		outPath := filepath.Join(pkgDir, pkgName+".go")
		if err := os.WriteFile(outPath, []byte(src), 0644); err != nil {
			return fmt.Errorf("write state machine %s: %w", d.ID, err)
		}
	}

	return nil
}

// generateStateMachineSource generates the Go source for a state machine package.
func generateStateMachineSource(d *statemachine.StateDiagram, pkgName string) string {
	var buf strings.Builder

	buf.WriteString(fmt.Sprintf("// Code generated by fullend gen — do not edit.\n"))
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	buf.WriteString("import (\n\t\"fmt\"\n\t\"os\"\n)\n\n")

	// State constants.
	states := make([]string, len(d.States))
	copy(states, d.States)
	sort.Strings(states)

	buf.WriteString("// State constants.\nconst (\n")
	for _, s := range states {
		constName := ucFirst(s)
		buf.WriteString(fmt.Sprintf("\tState%s = %q\n", constName, s))
	}
	buf.WriteString(")\n\n")

	// Determine the status field type from the diagram.
	fieldType := inferFieldType(d)

	// Input type — SSaC codegen generates e.g. coursestate.Input{Status: course.Published}.
	buf.WriteString("// Input holds the state field value for transition checks.\n")
	buf.WriteString("type Input struct {\n")
	buf.WriteString("\tStatus interface{}\n")
	buf.WriteString("}\n\n")

	// transitionKey type.
	buf.WriteString("type transitionKey struct {\n\tfrom  string\n\tevent string\n}\n\n")

	// Transitions map.
	buf.WriteString("var transitions = map[transitionKey]string{\n")
	for _, t := range d.Transitions {
		buf.WriteString(fmt.Sprintf("\t{%q, %q}: %q,\n", t.From, t.Event, t.To))
	}
	buf.WriteString("}\n\n")

	// CanTransition function — accepts Input, resolves state internally.
	switch fieldType {
	case "bool":
		buf.WriteString(generateBoolCanTransition(d))
	default:
		// String-based status field.
		buf.WriteString(`// CanTransition checks if the given event is valid from the current state.
// Set DISABLE_STATE_CHECK=1 to bypass state transition checks.
func CanTransition(input Input, event string) error {
	if os.Getenv("DISABLE_STATE_CHECK") == "1" {
		return nil
	}
	status, _ := input.Status.(string)
	_, ok := transitions[transitionKey{from: status, event: event}]
	if !ok {
		return fmt.Errorf("cannot transition from %q via %q", status, event)
	}
	return nil
}
`)
	}

	return buf.String()
}

// generateBoolCanTransition generates CanTransition for boolean status fields.
func generateBoolCanTransition(d *statemachine.StateDiagram) string {
	// Find the mapping: which state name corresponds to true/false.
	// Convention: state name matching a common boolean pattern → true.
	// "published" → true, "unpublished" → false, etc.
	trueState, falseState := inferBoolStates(d)

	var buf strings.Builder
	buf.WriteString("// CanTransition checks if the given event is valid from the current state.\n")
	buf.WriteString("// Set DISABLE_STATE_CHECK=1 to bypass state transition checks.\n")
	buf.WriteString("func CanTransition(input Input, event string) error {\n")
	buf.WriteString("\tif os.Getenv(\"DISABLE_STATE_CHECK\") == \"1\" {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tcurrent := resolveState(input.Status)\n")
	buf.WriteString("\t_, ok := transitions[transitionKey{from: current, event: event}]\n")
	buf.WriteString("\tif !ok {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"cannot transition from %q via %q\", current, event)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func resolveState(v interface{}) string {\n")
	buf.WriteString("\tswitch val := v.(type) {\n")
	buf.WriteString("\tcase bool:\n")
	buf.WriteString("\t\tif val {\n")
	buf.WriteString(fmt.Sprintf("\t\t\treturn %q\n", trueState))
	buf.WriteString("\t\t}\n")
	buf.WriteString(fmt.Sprintf("\t\treturn %q\n", falseState))
	buf.WriteString("\tcase string:\n")
	buf.WriteString("\t\treturn val\n")
	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\treturn \"\"\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	return buf.String()
}

// inferFieldType determines if the status field is boolean or string-based.
// Heuristic: if exactly 2 live states (excluding terminal states like "deleted")
// and one has "un" prefix of the other, it's boolean.
func inferFieldType(d *statemachine.StateDiagram) string {
	// Collect non-terminal states (states that have outgoing transitions).
	hasOutgoing := make(map[string]bool)
	for _, t := range d.Transitions {
		hasOutgoing[t.From] = true
	}

	// If we can find a pair like published/unpublished, it's boolean.
	for _, s := range d.States {
		negated := "un" + s
		for _, s2 := range d.States {
			if s2 == negated {
				return "bool"
			}
		}
	}

	return "string"
}

// inferBoolStates returns (trueState, falseState) for boolean diagrams.
func inferBoolStates(d *statemachine.StateDiagram) (string, string) {
	for _, s := range d.States {
		negated := "un" + s
		for _, s2 := range d.States {
			if s2 == negated {
				return s, s2 // s = true, "un"+s = false
			}
		}
	}
	// Fallback: initial state = false.
	if d.InitialState != "" {
		for _, s := range d.States {
			if s != d.InitialState && s != "deleted" {
				return s, d.InitialState
			}
		}
	}
	return d.States[0], d.States[1]
}
