// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package db

import (
	"context"
	"encoding/json"
)

const actionCreate = `-- name: ActionCreate :one
INSERT INTO actions (workflow_id, action_type, payload_template, sequence_order)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, action_type, payload_template, sequence_order
`

type ActionCreateParams struct {
	WorkflowID      int64           `json:"workflow_id"`
	ActionType      string          `json:"action_type"`
	PayloadTemplate json.RawMessage `json:"payload_template"`
	SequenceOrder   int32           `json:"sequence_order"`
}

func (q *Queries) ActionCreate(ctx context.Context, arg ActionCreateParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, actionCreate,
		arg.WorkflowID,
		arg.ActionType,
		arg.PayloadTemplate,
		arg.SequenceOrder,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ActionType,
		&i.PayloadTemplate,
		&i.SequenceOrder,
	)
	return i, err
}

const actionListByWorkflowID = `-- name: ActionListByWorkflowID :many
SELECT id, workflow_id, action_type, payload_template, sequence_order FROM actions WHERE workflow_id = $1 ORDER BY sequence_order
`

func (q *Queries) ActionListByWorkflowID(ctx context.Context, workflowID int64) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, actionListByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Action{}
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.ActionType,
			&i.PayloadTemplate,
			&i.SequenceOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
