// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db

import (
	"context"
)

const executionCreate = `-- name: ExecutionCreate :one
INSERT INTO executions (workflow_id, org_id, status, credits_spent)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, org_id, status, credits_spent, executed_at
`

type ExecutionCreateParams struct {
	WorkflowID   int64  `json:"workflow_id"`
	OrgID        int64  `json:"org_id"`
	Status       string `json:"status"`
	CreditsSpent int32  `json:"credits_spent"`
}

func (q *Queries) ExecutionCreate(ctx context.Context, arg ExecutionCreateParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, executionCreate,
		arg.WorkflowID,
		arg.OrgID,
		arg.Status,
		arg.CreditsSpent,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}
