// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"
)

const organizationCreate = `-- name: OrganizationCreate :one
INSERT INTO organizations (name, plan_type, credits_balance)
VALUES ($1, $2, $3)
RETURNING id, name, plan_type, credits_balance
`

type OrganizationCreateParams struct {
	Name           string `json:"name"`
	PlanType       string `json:"plan_type"`
	CreditsBalance int32  `json:"credits_balance"`
}

func (q *Queries) OrganizationCreate(ctx context.Context, arg OrganizationCreateParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, organizationCreate, arg.Name, arg.PlanType, arg.CreditsBalance)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.CreditsBalance,
	)
	return i, err
}

const organizationFindByID = `-- name: OrganizationFindByID :one
SELECT id, name, plan_type, credits_balance FROM organizations WHERE id = $1
`

func (q *Queries) OrganizationFindByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, organizationFindByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.CreditsBalance,
	)
	return i, err
}
