// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (org_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, email, password_hash, role
`

type UserCreateParams struct {
	OrgID        int64  `json:"org_id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.OrgID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const userFindByEmail = `-- name: UserFindByEmail :one
SELECT id, org_id, email, password_hash, role FROM users WHERE email = $1
`

func (q *Queries) UserFindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const userFindByID = `-- name: UserFindByID :one
SELECT id, org_id, email, password_hash, role FROM users WHERE id = $1
`

func (q *Queries) UserFindByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}
