// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"
)

const workflowCreate = `-- name: WorkflowCreate :one
INSERT INTO workflows (org_id, title, trigger_event, status)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, title, trigger_event, status, created_at
`

type WorkflowCreateParams struct {
	OrgID        int64  `json:"org_id"`
	Title        string `json:"title"`
	TriggerEvent string `json:"trigger_event"`
	Status       string `json:"status"`
}

func (q *Queries) WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, workflowCreate,
		arg.OrgID,
		arg.Title,
		arg.TriggerEvent,
		arg.Status,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const workflowFindByID = `-- name: WorkflowFindByID :one
SELECT id, org_id, title, trigger_event, status, created_at FROM workflows WHERE id = $1
`

func (q *Queries) WorkflowFindByID(ctx context.Context, id int64) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, workflowFindByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const workflowListByOrgID = `-- name: WorkflowListByOrgID :many
SELECT id, org_id, title, trigger_event, status, created_at FROM workflows WHERE org_id = $1
`

func (q *Queries) WorkflowListByOrgID(ctx context.Context, orgID int64) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, workflowListByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.TriggerEvent,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowUpdateStatus = `-- name: WorkflowUpdateStatus :exec
UPDATE workflows SET status = $1 WHERE id = $2
`

type WorkflowUpdateStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) WorkflowUpdateStatus(ctx context.Context, arg WorkflowUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, workflowUpdateStatus, arg.Status, arg.ID)
	return err
}
