// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Action defines model for Action.
type Action struct {
	ActionType      *string `json:"action_type,omitempty"`
	Id              *int64  `json:"id,omitempty"`
	PayloadTemplate *string `json:"payload_template,omitempty"`
	SequenceOrder   *int    `json:"sequence_order,omitempty"`
	WorkflowId      *int64  `json:"workflow_id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// ExecutionLog defines model for ExecutionLog.
type ExecutionLog struct {
	CreditsSpent *int       `json:"credits_spent,omitempty"`
	ExecutedAt   *time.Time `json:"executed_at,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	OrgId        *int64     `json:"org_id,omitempty"`
	Status       *string    `json:"status,omitempty"`
	WorkflowId   *int64     `json:"workflow_id,omitempty"`
}

// Workflow defines model for Workflow.
type Workflow struct {
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	OrgId        *int64     `json:"org_id,omitempty"`
	Status       *string    `json:"status,omitempty"`
	Title        *string    `json:"title,omitempty"`
	TriggerEvent *string    `json:"trigger_event,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    string `json:"email"`
	OrgName  string `json:"org_name"`
	Password string `json:"password"`
}

// CreateWorkflowJSONBody defines parameters for CreateWorkflow.
type CreateWorkflowJSONBody struct {
	Title        string `json:"title"`
	TriggerEvent string `json:"trigger_event"`
}

// AddActionJSONBody defines parameters for AddAction.
type AddActionJSONBody struct {
	ActionType      string  `json:"action_type"`
	PayloadTemplate *string `json:"payload_template,omitempty"`
	SequenceOrder   int     `json:"sequence_order"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody CreateWorkflowJSONBody

// AddActionJSONRequestBody defines body for AddAction for application/json ContentType.
type AddActionJSONRequestBody AddActionJSONBody
