// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gigs.sql

package db

import (
	"context"
)

const gigAssignFreelancer = `-- name: GigAssignFreelancer :exec
UPDATE gigs SET freelancer_id = $2, status = 'in_progress' WHERE id = $1
`

type GigAssignFreelancerParams struct {
	ID           int64 `json:"id"`
	FreelancerID int64 `json:"freelancer_id"`
}

func (q *Queries) GigAssignFreelancer(ctx context.Context, arg GigAssignFreelancerParams) error {
	_, err := q.db.ExecContext(ctx, gigAssignFreelancer, arg.ID, arg.FreelancerID)
	return err
}

const gigCreate = `-- name: GigCreate :one
INSERT INTO gigs (client_id, title, description, budget) VALUES ($1, $2, $3, $4) RETURNING id, client_id, title, description, budget, status, freelancer_id, created_at
`

type GigCreateParams struct {
	ClientID    int64  `json:"client_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Budget      int32  `json:"budget"`
}

func (q *Queries) GigCreate(ctx context.Context, arg GigCreateParams) (Gig, error) {
	row := q.db.QueryRowContext(ctx, gigCreate,
		arg.ClientID,
		arg.Title,
		arg.Description,
		arg.Budget,
	)
	var i Gig
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Budget,
		&i.Status,
		&i.FreelancerID,
		&i.CreatedAt,
	)
	return i, err
}

const gigFindByID = `-- name: GigFindByID :one
SELECT id, client_id, title, description, budget, status, freelancer_id, created_at FROM gigs WHERE id = $1
`

func (q *Queries) GigFindByID(ctx context.Context, id int64) (Gig, error) {
	row := q.db.QueryRowContext(ctx, gigFindByID, id)
	var i Gig
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Budget,
		&i.Status,
		&i.FreelancerID,
		&i.CreatedAt,
	)
	return i, err
}

const gigList = `-- name: GigList :many
SELECT id, client_id, title, description, budget, status, freelancer_id, created_at FROM gigs
`

func (q *Queries) GigList(ctx context.Context) ([]Gig, error) {
	rows, err := q.db.QueryContext(ctx, gigList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gig{}
	for rows.Next() {
		var i Gig
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Title,
			&i.Description,
			&i.Budget,
			&i.Status,
			&i.FreelancerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gigUpdateStatus = `-- name: GigUpdateStatus :exec
UPDATE gigs SET status = $2 WHERE id = $1
`

type GigUpdateStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) GigUpdateStatus(ctx context.Context, arg GigUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, gigUpdateStatus, arg.ID, arg.Status)
	return err
}
