// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
)

const transactionCreate = `-- name: TransactionCreate :one
INSERT INTO transactions (gig_id, tx_type, amount) VALUES ($1, $2, $3) RETURNING id, gig_id, tx_type, amount, created_at
`

type TransactionCreateParams struct {
	GigID  int64  `json:"gig_id"`
	TxType string `json:"tx_type"`
	Amount int32  `json:"amount"`
}

func (q *Queries) TransactionCreate(ctx context.Context, arg TransactionCreateParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, transactionCreate, arg.GigID, arg.TxType, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.GigID,
		&i.TxType,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
