//ff:func feature=gen-gogin type=generator control=sequence topic=ddl
//ff:what GenerateSchema — DDL 파일들을 FK 위상순서로 병합해 schema.sql 단일 산출

package db

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/park-jun-woo/fullend/pkg/parser/ddl"
)

// GenerateSchema produces artifacts/backend/db/schema.sql combining all DDL files in
// FK-topological order. Returns (tables, totalSeeds, error).
func GenerateSchema(tables []ddl.Table, cfg Config) (int, int, error) {
	order, err := SortTablesByFK(tables)
	if err != nil {
		return 0, 0, err
	}
	tableByName := indexTablesByName(tables)
	autoSeedSQL := ""
	if cfg.AutoNobodySeed {
		autoSeedSQL = buildAutoNobodySeeds(tables, tableByName)
	}
	src, totalSeeds := assembleSchemaSQL(order, tableByName, cfg.SpecsDDLDir, autoSeedSQL)

	outDir := filepath.Join(cfg.ArtifactsDir, "backend", "db")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return 0, 0, fmt.Errorf("create schema dir: %w", err)
	}
	header := fmt.Sprintf("-- Auto-generated by fullend gen — do not edit.\n-- Source: %s\n-- Generated: %s\n\n",
		cfg.SpecsDDLDir, time.Now().UTC().Format(time.RFC3339))
	outPath := filepath.Join(outDir, "schema.sql")
	if err := os.WriteFile(outPath, []byte(header+src), 0644); err != nil {
		return 0, 0, fmt.Errorf("write schema.sql: %w", err)
	}
	return len(order), totalSeeds, nil
}
