// Code generated by fullend gen — do not edit.
//fullend:gen ssot=states/proposal.md contract=19880c1
package proposalstate

import (
	"fmt"
	"os"
)

// State constants.
const (
	StateAccepted = "accepted"
	StatePending = "pending"
	StateRejected = "rejected"
)

// Input holds the state field value for transition checks.
type Input struct {
	Status interface{}
}

type transitionKey struct {
	from  string
	event string
}

var transitions = map[transitionKey]string{
	{"pending", "AcceptProposal"}: "accepted",
	{"pending", "RejectProposal"}: "rejected",
}

// CanTransition checks if the given event is valid from the current state.
// Set DISABLE_STATE_CHECK=1 to bypass state transition checks.
func CanTransition(input Input, event string) error {
	if os.Getenv("DISABLE_STATE_CHECK") == "1" {
		return nil
	}
	status, _ := input.Status.(string)
	_, ok := transitions[transitionKey{from: status, event: event}]
	if !ok {
		return fmt.Errorf("cannot transition from %q via %q", status, event)
	}
	return nil
}
